/* ============================================================================
 * ReadH5OinaData V&V test suite.
 *
 * Verification is established INDEPENDENTLY of any DREAM3D output, per the V&V
 * policy (src/Plugins/OrientationAnalysis/vv/ReadH5OinaDataFilter.md). There is
 * no DREAM3D 6.5.171 H5OINA importer to compare against, so the oracle carries
 * the whole burden:
 *
 *  - .h5oina parsing     : Class 2 (EbsdLib reference, trusted & NOT re-tested).
 *                          EbsdLib's H5OINAReader owns HDF5 traversal, header and
 *                          phase parsing, required-dataset enforcement and its own
 *                          error codes. We do not re-test any of that; we do pin
 *                          the codes it hands back through the filter.
 *  - SIMPLNX value-add   : Class 1 (analytical) + Class 4 (invariant). The filter's
 *                          value-add is deterministic plumbing on top of the reader:
 *                          geometry construction from the first scan's header, array
 *                          creation and typing, per-scan slab offsets, the verbatim
 *                          column copies, the uint8 -> int32 Phase widening, the
 *                          EDAX hexagonal alignment applied to phi2, ensemble slot-0
 *                          defaults and per-phase fill, and the malformed-input
 *                          guards. The toy .h5oina fixtures below are written by
 *                          this file with H5Lite and every expected value is derived
 *                          from the fixture spec, never from observed output.
 *  - Real AZtec file     : Class 2 independent readback. The archived production
 *                          H5Oina_Test_Data.h5oina is compared against a readback of
 *                          its own Data group datasets performed with H5Lite, i.e. the
 *                          raw file bytes, bypassing H5OINAReader entirely. An
 *                          equivalent h5py readback in a second language is recorded
 *                          in the V&V working folder, described in
 *                          vv/provenance/ReadH5OinaDataFilter.md.
 *
 * Precision pinning (the ReadCtfData lesson): every floating-point value written
 * into a toy fixture below is a float32 literal stored as float32, so the file
 * round-trips it bit-for-bit and the verbatim copies are asserted with exact
 * equality. (The cell counts and the Laue and space group numbers are int32
 * scalars and five of the nine data columns are uint8, all of which round-trip
 * exactly as well. The production file's values are whatever AZtec wrote; that
 * test asserts exact equality too, but against an independent readback of the
 * file rather than against literals.)
 *
 * The hexagonal alignment adds 30 degrees expressed in radians, computed with a
 * double-precision intermediate and stored back as float32. Five fixture phi2
 * values -- 0.1F and 0.34F, used in Fixture A and in Fixture C's first scan, and
 * 0.09F, 0.22F and 0.35F in Fixture C's second scan -- are chosen because their
 * correctly-rounded float32 results DIFFER between a double-precision
 * intermediate and a float32 intermediate, so the expectations pin the shape of
 * the arithmetic and not merely its magnitude. Note that none of those five is an
 * exactly representable decimal, and that is deliberate: a dyadic value has
 * trailing zero mantissa bits, so adding the constant rounds to the same float32
 * either way and cannot separate the two paths. 0.25F, 0.5F and 0.75F are exactly
 * representable and are carried alongside on hexagonal points as controls whose
 * results are identical under either intermediate. The hexagonal phase's third
 * lattice angle, 2.0943952F -> 120.0F, is a sixth such discriminator: a float32
 * intermediate in the radians-to-degrees conversion would give 120.00000762939453F.
 * Every such literal was derived with IEEE-754 float32/float64 semantics in NumPy;
 * the derivation script and its recorded output are described in
 * vv/provenance/ReadH5OinaDataFilter.md.
 *
 * The archive's H5Oina_Test_Data.dream3d exemplar is no longer consulted: it was
 * generated by this very filter, so it is a self-oracle that pins "the filter
 * keeps doing what it did" rather than "the filter is right".
 * ========================================================================== */

#include "OrientationAnalysis/Filters/ReadH5OinaDataFilter.hpp"
#include "OrientationAnalysis/OrientationAnalysis_test_dirs.hpp"
#include "OrientationAnalysis/Parameters/OEMEbsdScanSelectionParameter.h"

#include "simplnx/DataStructure/DataArray.hpp"
#include "simplnx/DataStructure/Geometry/ImageGeom.hpp"
#include "simplnx/DataStructure/StringArray.hpp"
#include "simplnx/Parameters/BoolParameter.hpp"
#include "simplnx/Parameters/DataGroupCreationParameter.hpp"
#include "simplnx/Parameters/VectorParameter.hpp"
#include "simplnx/UnitTest/UnitTestCommon.hpp"

#include "H5Support/H5Lite.h"
#include "H5Support/H5Utilities.h"

#include <EbsdLib/Core/EbsdLibConstants.h>
#include <EbsdLib/IO/HKL/CtfConstants.h>
#include <EbsdLib/IO/TSL/AngConstants.h>

#include <catch2/catch.hpp>

#include <fmt/format.h>

#include <array>
#include <filesystem>
#include <string>
#include <vector>

namespace fs = std::filesystem;

using namespace nx::core;
using namespace nx::core::Constants;
using namespace H5Support;

namespace
{
const std::string k_CellAttributeMatrixName = "Cell Data";
const std::string k_CellEnsembleAttributeMatrixName = "Cell Ensemble Data";
const DataPath k_ImageGeomPath({ImageGeom::k_TypeName});
const DataPath k_CellAMPath = k_ImageGeomPath.createChildPath(k_CellAttributeMatrixName);
const DataPath k_EnsembleAMPath = k_ImageGeomPath.createChildPath(k_CellEnsembleAttributeMatrixName);

// EbsdLib/IO/HKL/CtfConstants.h LaueGroupTable: 9 = LG_Hexagonal_High, 11 = LG_Cubic_High.
// EbsdLib/Core/EbsdLibConstants.h: Hexagonal_High = 0, Cubic_High = 1, UnknownCrystalStructure = 999.
constexpr int32 k_LaueHexagonalHigh = 9;
constexpr int32 k_LaueCubicHigh = 11;

//------------------------------------------------------------------------------
// Toy .h5oina fixture description. Written out in full, the dataset set below is
// exactly the minimum H5OINAReader requires: the four Header scalars, one or more
// Phases/<n> groups carrying Phase Name / Lattice Dimensions / Lattice Angles /
// Laue Group / Space Group, and the nine Data datasets it reads unconditionally.
// The root Manufacturer / Software Version / Index datasets are written for
// realism only -- the reader never reads them.
//
// The guard fixtures deliberately depart from that minimum: `omitBandsDataset`
// and `omitLatticeAngles` drop a required dataset outright, and `groupName`
// overrides the phase index that the group name carries. The remaining guard
// fixtures keep the full dataset set but give it values a well formed file would
// not have.
//------------------------------------------------------------------------------
struct PhaseSpec
{
  std::string name;
  int32 laueGroup = k_LaueCubicHigh;
  int32 spaceGroup = 225;
  std::array<float32, 3> latticeDimensions = {1.0F, 1.0F, 1.0F};
  // Lattice angles as an H5OINA file stores them: RADIANS.
  std::array<float32, 3> latticeAngles = {1.5707964F, 1.5707964F, 1.5707964F};
  // Group name override; empty means "use the phase's 1-based position".
  std::string groupName;
  bool omitLatticeAngles = false;
};

struct ScanSpec
{
  std::string name = "1";
  int32 xCells = 1;
  int32 yCells = 1;
  float32 xStep = 1.0F;
  float32 yStep = 1.0F;
  std::vector<PhaseSpec> phases;
  std::vector<uint8> phase;
  std::vector<uint8> bandContrast;
  std::vector<uint8> bandSlope;
  std::vector<uint8> bands;
  std::vector<uint8> error;
  std::vector<float32> euler; // 3 components per point, interleaved
  std::vector<float32> mad;
  std::vector<float32> x;
  std::vector<float32> y;
  // Guard-fixture switches.
  bool omitBandsDataset = false;
};

//------------------------------------------------------------------------------
template <typename T>
void WriteVector(hid_t gid, const std::string& name, const std::vector<hsize_t>& dims, const std::vector<T>& data)
{
  const herr_t err = H5Lite::writeVectorDataset<T>(gid, name, dims, data);
  REQUIRE(err >= 0);
}

//------------------------------------------------------------------------------
hid_t OpenOrCreateGroup(hid_t fileId, const std::string& path)
{
  const hid_t err = H5Utilities::createGroupsFromPath(path, fileId);
  REQUIRE(err >= 0);
  const hid_t gid = H5Gopen(fileId, path.c_str(), H5P_DEFAULT);
  REQUIRE(gid >= 0);
  return gid;
}

//------------------------------------------------------------------------------
// Writes the fixture to <binary test output dir>/<fileName> and returns the path.
//------------------------------------------------------------------------------
fs::path WriteH5OinaFixture(const std::string& fileName, const std::vector<ScanSpec>& scans, bool writeFormatVersion = true, const std::string& formatVersion = "5.0")
{
  const fs::path filePath = fs::path(unit_test::k_BinaryTestOutputDir.view()) / fileName;
  const hid_t fileId = H5Fcreate(filePath.string().c_str(), H5F_ACC_TRUNC, H5P_DEFAULT, H5P_DEFAULT);
  REQUIRE(fileId >= 0);

  if(writeFormatVersion)
  {
    REQUIRE(H5Lite::writeStringDataset(fileId, ebsdlib::H5OINA::FormatVersion, formatVersion) >= 0);
  }
  // Inert realism -- the reader never reads these three.
  REQUIRE(H5Lite::writeStringDataset(fileId, ebsdlib::H5OINA::Manufacturer, "Oxford Instruments") >= 0);
  REQUIRE(H5Lite::writeStringDataset(fileId, ebsdlib::H5OINA::SoftwareVersion, "V&V toy fixture") >= 0);
  REQUIRE(H5Lite::writeStringDataset(fileId, ebsdlib::H5OINA::Index, "1") >= 0);

  for(const ScanSpec& scan : scans)
  {
    const std::string headerPath = fmt::format("{}/{}/{}", scan.name, ebsdlib::H5OINA::EBSD, ebsdlib::H5OINA::Header);
    const hid_t headerGid = OpenOrCreateGroup(fileId, headerPath);
    REQUIRE(H5Lite::writeScalarDataset<int32>(headerGid, ebsdlib::H5OINA::XCells, scan.xCells) >= 0);
    REQUIRE(H5Lite::writeScalarDataset<int32>(headerGid, ebsdlib::H5OINA::YCells, scan.yCells) >= 0);
    REQUIRE(H5Lite::writeScalarDataset<float32>(headerGid, ebsdlib::H5OINA::XStep, scan.xStep) >= 0);
    REQUIRE(H5Lite::writeScalarDataset<float32>(headerGid, ebsdlib::H5OINA::YStep, scan.yStep) >= 0);

    for(usize i = 0; i < scan.phases.size(); i++)
    {
      const PhaseSpec& phaseSpec = scan.phases[i];
      const std::string groupName = phaseSpec.groupName.empty() ? std::to_string(i + 1) : phaseSpec.groupName;
      const hid_t phaseGid = OpenOrCreateGroup(fileId, fmt::format("{}/{}/{}", headerPath, ebsdlib::H5OINA::Phases, groupName));
      REQUIRE(H5Lite::writeStringDataset(phaseGid, ebsdlib::H5OINA::PhaseName, phaseSpec.name) >= 0);
      WriteVector<float32>(phaseGid, ebsdlib::H5OINA::LatticeDimensions, {1, 3}, {phaseSpec.latticeDimensions[0], phaseSpec.latticeDimensions[1], phaseSpec.latticeDimensions[2]});
      if(!phaseSpec.omitLatticeAngles)
      {
        WriteVector<float32>(phaseGid, ebsdlib::H5OINA::LatticeAngles, {1, 3}, {phaseSpec.latticeAngles[0], phaseSpec.latticeAngles[1], phaseSpec.latticeAngles[2]});
      }
      REQUIRE(H5Lite::writeScalarDataset<int32>(phaseGid, ebsdlib::H5OINA::LaueGroup, phaseSpec.laueGroup) >= 0);
      REQUIRE(H5Lite::writeScalarDataset<int32>(phaseGid, ebsdlib::H5OINA::SpaceGroup, phaseSpec.spaceGroup) >= 0);
      REQUIRE(H5Gclose(phaseGid) >= 0);
    }
    REQUIRE(H5Gclose(headerGid) >= 0);

    const hid_t dataGid = OpenOrCreateGroup(fileId, fmt::format("{}/{}/{}", scan.name, ebsdlib::H5OINA::EBSD, ebsdlib::H5OINA::Data));
    const auto pointCount = static_cast<hsize_t>(scan.phase.size());
    WriteVector<uint8>(dataGid, ebsdlib::H5OINA::BandContrast, {pointCount}, scan.bandContrast);
    WriteVector<uint8>(dataGid, ebsdlib::H5OINA::BandSlope, {pointCount}, scan.bandSlope);
    if(!scan.omitBandsDataset)
    {
      WriteVector<uint8>(dataGid, ebsdlib::H5OINA::Bands, {pointCount}, scan.bands);
    }
    WriteVector<uint8>(dataGid, ebsdlib::H5OINA::Error, {pointCount}, scan.error);
    WriteVector<float32>(dataGid, ebsdlib::H5OINA::Euler, {pointCount, 3}, scan.euler);
    WriteVector<float32>(dataGid, ebsdlib::H5OINA::MeanAngularDeviation, {pointCount}, scan.mad);
    WriteVector<uint8>(dataGid, ebsdlib::H5OINA::Phase, {pointCount}, scan.phase);
    WriteVector<float32>(dataGid, ebsdlib::H5OINA::X, {pointCount}, scan.x);
    WriteVector<float32>(dataGid, ebsdlib::H5OINA::Y, {pointCount}, scan.y);
    REQUIRE(H5Gclose(dataGid) >= 0);
  }

  REQUIRE(H5Fclose(fileId) >= 0);
  return filePath;
}

//------------------------------------------------------------------------------
// Fixture phases.
//------------------------------------------------------------------------------
// Hexagonal: Laue group 9 -> CrystalStructure Hexagonal_High (0). Its lattice
// angles are 90/90/120 degrees written as radians, which is what an H5OINA file
// carries; the third angle differs from the second so a gamma slot that echoed
// beta would be visible.
const PhaseSpec k_HexPhase{"Hex Phase A", k_LaueHexagonalHigh, 194, {2.5F, 2.5F, 4.0F}, {1.5707964F, 1.5707964F, 2.0943952F}};
// Cubic: Laue group 11 -> CrystalStructure Cubic_High (1).
const PhaseSpec k_CubicPhase{"Cubic Phase B", k_LaueCubicHigh, 225, {3.5F, 3.5F, 3.5F}, {1.5707964F, 1.5707964F, 1.5707964F}};

//------------------------------------------------------------------------------
// Fixture A: one scan "1", 3 x 2 cells, XStep 0.25 / YStep 0.5, two phases.
//
// Points 0, 1 and 2 all carry phi2 = 0.1F on a hexagonal, a cubic and an
// unindexed (phase 0) point respectively, so the three expectations differ only
// through the alignment branch.
//------------------------------------------------------------------------------
ScanSpec MakeFixtureAScan()
{
  ScanSpec scan;
  scan.name = "1";
  scan.xCells = 3;
  scan.yCells = 2;
  scan.xStep = 0.25F;
  scan.yStep = 0.5F;
  scan.phases = {k_HexPhase, k_CubicPhase};
  scan.phase = {1, 2, 0, 2, 1, 1};
  scan.bandContrast = {10, 20, 30, 40, 50, 60};
  scan.bandSlope = {11, 21, 31, 41, 51, 61};
  scan.bands = {1, 2, 3, 4, 5, 6};
  scan.error = {0, 1, 0, 2, 0, 3};
  scan.euler = {
      0.25F, 0.125F, 0.1F,  // pt 0 hexagonal  -> phi2 shifted
      0.5F,  0.375F, 0.1F,  // pt 1 cubic      -> phi2 untouched
      0.75F, 0.625F, 0.1F,  // pt 2 unindexed  -> phi2 untouched
      1.0F,  0.875F, 0.75F, // pt 3 cubic      -> phi2 untouched
      1.25F, 1.125F, 0.34F, // pt 4 hexagonal  -> phi2 shifted
      1.5F,  1.375F, 0.25F, // pt 5 hexagonal  -> phi2 shifted (dyadic control)
  };
  scan.mad = {0.125F, 0.25F, 0.375F, 0.5F, 0.625F, 0.75F};
  scan.x = {0.0F, 0.25F, 0.5F, 0.0F, 0.25F, 0.5F};
  scan.y = {0.0F, 0.0F, 0.0F, 0.5F, 0.5F, 0.5F};
  return scan;
}

// Fixture A expected Euler with the alignment ON. The three shifted values are the
// correctly-rounded float32 results of double(phi2) + 30*(pi/180):
//   0.1F  -> 0.6235987544059753F  (a float32 intermediate would give 0.6235988140106201F)
//   0.34F -> 0.8635987639427185F  (a float32 intermediate would give 0.8635988235473633F)
//   0.25F -> 0.7735987901687622F  (identical under either intermediate -- the control)
// Adding the literal 30.0F, as a degree-valued importer would, gives 30.1F / 30.34F / 30.25F.
const std::vector<float32> k_FixtureAEulerAligned = {
    0.25F, 0.125F, 0.6235987544059753F, 0.5F, 0.375F, 0.1F, 0.75F, 0.625F, 0.1F, 1.0F, 0.875F, 0.75F, 1.25F, 1.125F, 0.8635987639427185F, 1.5F, 1.375F, 0.7735987901687622F,
};
// The same fixture with the alignment OFF: every value verbatim from the file.
const std::vector<float32> k_FixtureAEulerVerbatim = {
    0.25F, 0.125F, 0.1F, 0.5F, 0.375F, 0.1F, 0.75F, 0.625F, 0.1F, 1.0F, 0.875F, 0.75F, 1.25F, 1.125F, 0.34F, 1.5F, 1.375F, 0.25F,
};

//------------------------------------------------------------------------------
// Fixture B: two scans, 2 x 2 each, CUBIC only. With no hexagonal points the
// Euler array must be a pure verbatim copy, so any slab-placement error is
// visible directly. Scan "2"'s values are disjoint from scan "1"'s.
//------------------------------------------------------------------------------
ScanSpec MakeFixtureBScan1()
{
  ScanSpec scan;
  scan.name = "1";
  scan.xCells = 2;
  scan.yCells = 2;
  scan.xStep = 0.25F;
  scan.yStep = 0.5F;
  scan.phases = {k_CubicPhase};
  scan.phase = {1, 1, 1, 1};
  scan.bandContrast = {10, 11, 12, 13};
  scan.bandSlope = {20, 21, 22, 23};
  scan.bands = {1, 2, 3, 4};
  scan.error = {0, 1, 2, 3};
  scan.euler = {0.125F, 0.25F, 0.375F, 0.5F, 0.625F, 0.75F, 0.875F, 1.0F, 1.125F, 1.25F, 1.375F, 1.5F};
  scan.mad = {0.125F, 0.25F, 0.375F, 0.5F};
  scan.x = {0.0F, 0.25F, 0.0F, 0.25F};
  scan.y = {0.0F, 0.0F, 0.5F, 0.5F};
  return scan;
}

ScanSpec MakeFixtureBScan2()
{
  ScanSpec scan = MakeFixtureBScan1();
  scan.name = "2";
  scan.bandContrast = {110, 111, 112, 113};
  scan.bandSlope = {120, 121, 122, 123};
  scan.bands = {5, 6, 7, 8};
  scan.error = {4, 5, 6, 7};
  scan.euler = {2.125F, 2.25F, 2.375F, 2.5F, 2.625F, 2.75F, 2.875F, 3.0F, 3.125F, 3.25F, 3.375F, 3.5F};
  scan.mad = {1.125F, 1.25F, 1.375F, 1.5F};
  // Every column has to differ from scan 1's, or a slab-placement error in that
  // column cannot be detected across the two slabs. The phase group set is kept
  // identical because the ensemble arrays are shared by every stacked scan; only
  // the per-point phase VALUES differ, using the reserved unindexed value 0.
  scan.phase = {1, 0, 1, 0};
  scan.x = {1.0F, 1.25F, 1.0F, 1.25F};
  scan.y = {1.0F, 1.0F, 1.5F, 1.5F};
  return scan;
}

//------------------------------------------------------------------------------
// Fixture C: two scans, 2 x 2 each, every point HEXAGONAL. A shift applied to
// the wrong slab, or applied more than once to slab 0, changes values that are
// pinned exactly here.
//------------------------------------------------------------------------------
ScanSpec MakeFixtureCScan1()
{
  ScanSpec scan;
  scan.name = "1";
  scan.xCells = 2;
  scan.yCells = 2;
  scan.xStep = 0.5F;
  scan.yStep = 0.25F;
  scan.phases = {k_HexPhase};
  scan.phase = {1, 1, 1, 1};
  scan.bandContrast = {30, 31, 32, 33};
  scan.bandSlope = {40, 41, 42, 43};
  scan.bands = {1, 2, 3, 4};
  scan.error = {0, 0, 0, 0};
  scan.euler = {0.25F, 0.5F, 0.1F, 0.75F, 1.0F, 0.34F, 1.25F, 1.5F, 0.25F, 1.75F, 2.0F, 0.5F};
  scan.mad = {0.125F, 0.25F, 0.375F, 0.5F};
  scan.x = {0.0F, 0.5F, 0.0F, 0.5F};
  scan.y = {0.0F, 0.0F, 0.25F, 0.25F};
  return scan;
}

ScanSpec MakeFixtureCScan2()
{
  ScanSpec scan = MakeFixtureCScan1();
  scan.name = "2";
  scan.bandContrast = {130, 131, 132, 133};
  scan.bandSlope = {140, 141, 142, 143};
  scan.bands = {5, 6, 7, 8};
  scan.error = {1, 1, 1, 1};
  scan.euler = {2.25F, 2.5F, 0.09F, 2.75F, 3.0F, 0.22F, 3.25F, 3.5F, 0.75F, 3.75F, 4.0F, 0.35F};
  scan.mad = {1.125F, 1.25F, 1.375F, 1.5F};
  return scan;
}

// Fixture C expected Euler across both slabs with the alignment ON. Every phi2 is
// float32(double(phi2) + 30*(pi/180)); 0.1F/0.34F in slab 0 and 0.09F/0.22F/0.35F
// in slab 1 separate a double intermediate from a float32 one, while 0.25F, 0.5F
// and 0.75F round identically under either.
const std::vector<float32> k_FixtureCEulerAligned = {
    // slab 0 (scan "1")
    0.25F,
    0.5F,
    0.6235987544059753F,
    0.75F,
    1.0F,
    0.8635987639427185F,
    1.25F,
    1.5F,
    0.7735987901687622F,
    1.75F,
    2.0F,
    1.0235987901687622F,
    // slab 1 (scan "2")
    2.25F,
    2.5F,
    0.6135987639427185F,
    2.75F,
    3.0F,
    0.7435987591743469F,
    3.25F,
    3.5F,
    1.2735987901687622F,
    3.75F,
    4.0F,
    0.8735987544059753F,
};

//------------------------------------------------------------------------------
Arguments MakeArgs(const fs::path& inputFile, const std::list<std::string>& scanNames, float32 zSpacing = 1.0F, bool hexAlignment = true, bool convertPhaseToInt32 = true, bool readPatternData = false,
                   uint32 stackingOrder = RefFrameZDir::k_LowtoHigh)
{
  Arguments args;
  const OEMEbsdScanSelectionParameter::ValueType scanSelections = {inputFile, stackingOrder, scanNames};
  args.insertOrAssign(ReadH5OinaDataFilter::k_SelectedScanNames_Key, std::make_any<OEMEbsdScanSelectionParameter::ValueType>(scanSelections));
  args.insertOrAssign(ReadH5OinaDataFilter::k_ZSpacing_Key, std::make_any<float32>(zSpacing));
  args.insertOrAssign(ReadH5OinaDataFilter::k_Origin_Key, std::make_any<VectorFloat32Parameter::ValueType>(std::vector<float32>(3, 0.0F)));
  args.insertOrAssign(ReadH5OinaDataFilter::k_ReadPatternData_Key, std::make_any<bool>(readPatternData));
  args.insertOrAssign(ReadH5OinaDataFilter::k_EdaxHexagonalAlignment_Key, std::make_any<bool>(hexAlignment));
  args.insertOrAssign(ReadH5OinaDataFilter::k_ConvertPhaseToInt32_Key, std::make_any<bool>(convertPhaseToInt32));
  args.insertOrAssign(ReadH5OinaDataFilter::k_CreatedImageGeometryPath_Key, std::make_any<DataPath>(k_ImageGeomPath));
  args.insertOrAssign(ReadH5OinaDataFilter::k_CellAttributeMatrixName_Key, std::make_any<std::string>(k_CellAttributeMatrixName));
  args.insertOrAssign(ReadH5OinaDataFilter::k_CellEnsembleAttributeMatrixName_Key, std::make_any<std::string>(k_CellEnsembleAttributeMatrixName));
  return args;
}

//------------------------------------------------------------------------------
template <typename T>
void CompareArrayValues(const DataStructure& dataStructure, const DataPath& arrayPath, const std::vector<T>& expected)
{
  REQUIRE_NOTHROW(dataStructure.getDataRefAs<DataArray<T>>(arrayPath));
  const auto& dataArrayRef = dataStructure.getDataRefAs<DataArray<T>>(arrayPath);
  REQUIRE(dataArrayRef.getSize() == expected.size());
  for(usize i = 0; i < expected.size(); i++)
  {
    INFO(fmt::format("Array '{}' index {}", arrayPath.toString(), i));
    REQUIRE(dataArrayRef[i] == expected[i]);
  }
}

//------------------------------------------------------------------------------
void CompareStringArrayValues(const DataStructure& dataStructure, const DataPath& arrayPath, const std::vector<std::string>& expected)
{
  REQUIRE_NOTHROW(dataStructure.getDataRefAs<StringArray>(arrayPath));
  const auto& stringArrayRef = dataStructure.getDataRefAs<StringArray>(arrayPath);
  REQUIRE(stringArrayRef.getNumberOfTuples() == expected.size());
  for(usize i = 0; i < expected.size(); i++)
  {
    INFO(fmt::format("Array '{}' index {}", arrayPath.toString(), i));
    REQUIRE(stringArrayRef[i] == expected[i]);
  }
}

//------------------------------------------------------------------------------
// Reads a dataset straight out of a .h5oina with H5Lite, i.e. from the file
// bytes, without involving H5OINAReader. Used by the real-file Class 2 readback.
//------------------------------------------------------------------------------
template <typename T>
std::vector<T> ReadRawDataset(const fs::path& filePath, const std::string& datasetPath)
{
  // H5Utilities::closeFile() takes its argument by non-const reference and assigns -1 to
  // it, so this identifier cannot be const.
  hid_t fileId = H5Utilities::openFile(filePath.string(), true);
  REQUIRE(fileId >= 0);
  std::vector<T> data;
  const herr_t err = H5Lite::readVectorDataset<T>(fileId, datasetPath, data);
  REQUIRE(err >= 0);
  REQUIRE(H5Utilities::closeFile(fileId) >= 0);
  return data;
}
} // namespace

//------------------------------------------------------------------------------
// Class 1 (analytical) + Class 4 (invariant) oracle over Fixture A with the
// shipped parameter defaults (hexagonal alignment ON, Phase widened to int32).
// Every expected value below is derived from the fixture spec above.
//------------------------------------------------------------------------------
TEST_CASE("OrientationAnalysis::ReadH5OinaDataFilter: Class 1 Analytical Oracle", "[OrientationAnalysis][ReadH5OinaDataFilter]")
{
  UnitTest::LoadPlugins();

  const fs::path inputFile = WriteH5OinaFixture("read_h5oina_vv_oracle.h5oina", {MakeFixtureAScan()});

  ReadH5OinaDataFilter filter;
  DataStructure dataStructure;
  const Arguments args = MakeArgs(inputFile, {"1"}, 0.75F);

  auto preflightResult = filter.preflight(dataStructure, args);
  SIMPLNX_RESULT_REQUIRE_VALID(preflightResult.outputActions);

  auto executeResult = filter.execute(dataStructure, args);
  SIMPLNX_RESULT_REQUIRE_VALID(executeResult.result);

  // --- Geometry: dims and spacing come from the header; the z extent is the
  // --- number of selected scans, the z spacing is the parameter, the origin is
  // --- the parameter, and the units are the filter's hard-coded Micrometer. ---
  REQUIRE_NOTHROW(dataStructure.getDataRefAs<ImageGeom>(k_ImageGeomPath));
  const auto& imageGeom = dataStructure.getDataRefAs<ImageGeom>(k_ImageGeomPath);
  REQUIRE(imageGeom.getDimensions() == SizeVec3(3, 2, 1));
  REQUIRE(imageGeom.getSpacing() == FloatVec3(0.25F, 0.5F, 0.75F));
  REQUIRE(imageGeom.getOrigin() == FloatVec3(0.0F, 0.0F, 0.0F));
  REQUIRE(imageGeom.getUnits() == IGeometry::LengthUnit::Micrometer);

  // --- Cell arrays: eight verbatim copies plus the aligned Euler array. -------
  CompareArrayValues<uint8>(dataStructure, k_CellAMPath.createChildPath(ebsdlib::H5OINA::BandContrast), {10, 20, 30, 40, 50, 60});
  CompareArrayValues<uint8>(dataStructure, k_CellAMPath.createChildPath(ebsdlib::H5OINA::BandSlope), {11, 21, 31, 41, 51, 61});
  CompareArrayValues<uint8>(dataStructure, k_CellAMPath.createChildPath(ebsdlib::H5OINA::Bands), {1, 2, 3, 4, 5, 6});
  CompareArrayValues<uint8>(dataStructure, k_CellAMPath.createChildPath(ebsdlib::H5OINA::Error), {0, 1, 0, 2, 0, 3});
  CompareArrayValues<float32>(dataStructure, k_CellAMPath.createChildPath(ebsdlib::H5OINA::MeanAngularDeviation), {0.125F, 0.25F, 0.375F, 0.5F, 0.625F, 0.75F});
  CompareArrayValues<float32>(dataStructure, k_CellAMPath.createChildPath(ebsdlib::H5OINA::X), {0.0F, 0.25F, 0.5F, 0.0F, 0.25F, 0.5F});
  CompareArrayValues<float32>(dataStructure, k_CellAMPath.createChildPath(ebsdlib::H5OINA::Y), {0.0F, 0.0F, 0.0F, 0.5F, 0.5F, 0.5F});
  // Phase is widened from the file's uint8 to int32 by default, values unchanged
  // (including the unindexed 0 at point 2).
  CompareArrayValues<int32>(dataStructure, k_CellAMPath.createChildPath(ebsdlib::H5OINA::Phase), {1, 2, 0, 2, 1, 1});
  CompareArrayValues<float32>(dataStructure, k_CellAMPath.createChildPath(ebsdlib::H5OINA::Euler), k_FixtureAEulerAligned);

  // --- Ensemble arrays: slot 0 is the reserved Invalid Phase, then one slot per
  // --- phase group in the file. Laue 9 -> Hexagonal_High (0), Laue 11 ->
  // --- Cubic_High (1). The file's radian lattice angles are stored as degrees,
  // --- matching the .ang and .ctf importers: 90, 90, 120 for the hexagonal
  // --- phase and 90, 90, 90 for the cubic one. -------------------------------
  CompareArrayValues<uint32>(dataStructure, k_EnsembleAMPath.createChildPath(ebsdlib::AngFile::CrystalStructures),
                             {ebsdlib::CrystalStructure::UnknownCrystalStructure, ebsdlib::CrystalStructure::Hexagonal_High, ebsdlib::CrystalStructure::Cubic_High});
  CompareStringArrayValues(dataStructure, k_EnsembleAMPath.createChildPath(ebsdlib::AngFile::MaterialName), {"Invalid Phase", "Hex Phase A", "Cubic Phase B"});
  CompareArrayValues<float32>(dataStructure, k_EnsembleAMPath.createChildPath(ebsdlib::AngFile::LatticeConstants),
                              {
                                  0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F,     // slot 0: Invalid Phase
                                  2.5F, 2.5F, 4.0F, 90.0F, 90.0F, 120.0F, // slot 1: Hex Phase A
                                  3.5F, 3.5F, 3.5F, 90.0F, 90.0F, 90.0F,  // slot 2: Cubic Phase B
                              });

  // Class 4 invariant: the ensemble matrix always carries exactly one more tuple
  // than the file has phase groups.
  REQUIRE(dataStructure.getDataRefAs<UInt32Array>(k_EnsembleAMPath.createChildPath(ebsdlib::AngFile::CrystalStructures)).getNumberOfTuples() == 3);

  UnitTest::CheckArraysInheritTupleDims(dataStructure);
}

//------------------------------------------------------------------------------
// The two value-transform options across their full 2 x 2 grid. Class 4
// invariants: the Phase values never change with either option, and the
// hexagonal shift never reaches a cubic or unindexed point.
//------------------------------------------------------------------------------
TEST_CASE("OrientationAnalysis::ReadH5OinaDataFilter: Conversion Option Combinations", "[OrientationAnalysis][ReadH5OinaDataFilter]")
{
  UnitTest::LoadPlugins();

  const fs::path inputFile = WriteH5OinaFixture("read_h5oina_vv_options.h5oina", {MakeFixtureAScan()});

  const auto hexAlignment = GENERATE(true, false);
  const auto convertPhaseToInt32 = GENERATE(true, false);

  DYNAMIC_SECTION("hexAlignment=" << hexAlignment << " convertPhaseToInt32=" << convertPhaseToInt32)
  {
    ReadH5OinaDataFilter filter;
    DataStructure dataStructure;
    const Arguments args = MakeArgs(inputFile, {"1"}, 1.0F, hexAlignment, convertPhaseToInt32);

    auto preflightResult = filter.preflight(dataStructure, args);
    SIMPLNX_RESULT_REQUIRE_VALID(preflightResult.outputActions);
    auto executeResult = filter.execute(dataStructure, args);
    SIMPLNX_RESULT_REQUIRE_VALID(executeResult.result);

    CompareArrayValues<float32>(dataStructure, k_CellAMPath.createChildPath(ebsdlib::H5OINA::Euler), hexAlignment ? k_FixtureAEulerAligned : k_FixtureAEulerVerbatim);

    if(convertPhaseToInt32)
    {
      CompareArrayValues<int32>(dataStructure, k_CellAMPath.createChildPath(ebsdlib::H5OINA::Phase), {1, 2, 0, 2, 1, 1});
    }
    else
    {
      CompareArrayValues<uint8>(dataStructure, k_CellAMPath.createChildPath(ebsdlib::H5OINA::Phase), {1, 2, 0, 2, 1, 1});
    }

    // The remaining columns are verbatim regardless of either option.
    CompareArrayValues<uint8>(dataStructure, k_CellAMPath.createChildPath(ebsdlib::H5OINA::Bands), {1, 2, 3, 4, 5, 6});
    CompareArrayValues<float32>(dataStructure, k_CellAMPath.createChildPath(ebsdlib::H5OINA::MeanAngularDeviation), {0.125F, 0.25F, 0.375F, 0.5F, 0.625F, 0.75F});

    UnitTest::CheckArraysInheritTupleDims(dataStructure);
  }
}

//------------------------------------------------------------------------------
// Two scans stacked into one geometry. Fixture B is cubic-only, so every cell
// array -- Euler included -- must be a verbatim copy landing in its own tuple
// slab: scan "1" in tuples [0, 4) and scan "2" in tuples [4, 8).
//------------------------------------------------------------------------------
TEST_CASE("OrientationAnalysis::ReadH5OinaDataFilter: Multi-Scan Slab Placement", "[OrientationAnalysis][ReadH5OinaDataFilter]")
{
  UnitTest::LoadPlugins();

  const fs::path inputFile = WriteH5OinaFixture("read_h5oina_vv_multiscan.h5oina", {MakeFixtureBScan1(), MakeFixtureBScan2()});

  ReadH5OinaDataFilter filter;
  DataStructure dataStructure;
  const Arguments args = MakeArgs(inputFile, {"1", "2"}, 0.5F);

  auto preflightResult = filter.preflight(dataStructure, args);
  SIMPLNX_RESULT_REQUIRE_VALID(preflightResult.outputActions);
  auto executeResult = filter.execute(dataStructure, args);
  SIMPLNX_RESULT_REQUIRE_VALID(executeResult.result);

  REQUIRE_NOTHROW(dataStructure.getDataRefAs<ImageGeom>(k_ImageGeomPath));
  const auto& imageGeom = dataStructure.getDataRefAs<ImageGeom>(k_ImageGeomPath);
  REQUIRE(imageGeom.getDimensions() == SizeVec3(2, 2, 2));
  REQUIRE(imageGeom.getSpacing() == FloatVec3(0.25F, 0.5F, 0.5F));

  // 24 Euler values: scan "1"'s 12 then scan "2"'s 12, each verbatim.
  CompareArrayValues<float32>(
      dataStructure, k_CellAMPath.createChildPath(ebsdlib::H5OINA::Euler),
      {
          0.125F, 0.25F, 0.375F, 0.5F, 0.625F, 0.75F, 0.875F, 1.0F, 1.125F, 1.25F, 1.375F, 1.5F, 2.125F, 2.25F, 2.375F, 2.5F, 2.625F, 2.75F, 2.875F, 3.0F, 3.125F, 3.25F, 3.375F, 3.5F,
      });
  CompareArrayValues<uint8>(dataStructure, k_CellAMPath.createChildPath(ebsdlib::H5OINA::BandContrast), {10, 11, 12, 13, 110, 111, 112, 113});
  CompareArrayValues<uint8>(dataStructure, k_CellAMPath.createChildPath(ebsdlib::H5OINA::BandSlope), {20, 21, 22, 23, 120, 121, 122, 123});
  CompareArrayValues<uint8>(dataStructure, k_CellAMPath.createChildPath(ebsdlib::H5OINA::Bands), {1, 2, 3, 4, 5, 6, 7, 8});
  CompareArrayValues<uint8>(dataStructure, k_CellAMPath.createChildPath(ebsdlib::H5OINA::Error), {0, 1, 2, 3, 4, 5, 6, 7});
  CompareArrayValues<float32>(dataStructure, k_CellAMPath.createChildPath(ebsdlib::H5OINA::MeanAngularDeviation), {0.125F, 0.25F, 0.375F, 0.5F, 1.125F, 1.25F, 1.375F, 1.5F});
  CompareArrayValues<int32>(dataStructure, k_CellAMPath.createChildPath(ebsdlib::H5OINA::Phase), {1, 1, 1, 1, 1, 0, 1, 0});
  CompareArrayValues<float32>(dataStructure, k_CellAMPath.createChildPath(ebsdlib::H5OINA::X), {0.0F, 0.25F, 0.0F, 0.25F, 1.0F, 1.25F, 1.0F, 1.25F});
  CompareArrayValues<float32>(dataStructure, k_CellAMPath.createChildPath(ebsdlib::H5OINA::Y), {0.0F, 0.0F, 0.5F, 0.5F, 1.0F, 1.0F, 1.5F, 1.5F});

  UnitTest::CheckArraysInheritTupleDims(dataStructure);
}

//------------------------------------------------------------------------------
// Two hexagonal scans. Every point takes the alignment, so the pinned values
// establish that the shift reaches scan "2"'s slab and is applied to scan "1"'s
// slab exactly once.
//------------------------------------------------------------------------------
TEST_CASE("OrientationAnalysis::ReadH5OinaDataFilter: Multi-Scan Hexagonal Alignment", "[OrientationAnalysis][ReadH5OinaDataFilter]")
{
  UnitTest::LoadPlugins();

  const fs::path inputFile = WriteH5OinaFixture("read_h5oina_vv_multiscan_hex.h5oina", {MakeFixtureCScan1(), MakeFixtureCScan2()});

  ReadH5OinaDataFilter filter;
  DataStructure dataStructure;
  const Arguments args = MakeArgs(inputFile, {"1", "2"}, 2.0F);

  auto preflightResult = filter.preflight(dataStructure, args);
  SIMPLNX_RESULT_REQUIRE_VALID(preflightResult.outputActions);
  auto executeResult = filter.execute(dataStructure, args);
  SIMPLNX_RESULT_REQUIRE_VALID(executeResult.result);

  REQUIRE_NOTHROW(dataStructure.getDataRefAs<ImageGeom>(k_ImageGeomPath));
  REQUIRE(dataStructure.getDataRefAs<ImageGeom>(k_ImageGeomPath).getDimensions() == SizeVec3(2, 2, 2));
  REQUIRE(dataStructure.getDataRefAs<ImageGeom>(k_ImageGeomPath).getSpacing() == FloatVec3(0.5F, 0.25F, 2.0F));

  CompareArrayValues<float32>(dataStructure, k_CellAMPath.createChildPath(ebsdlib::H5OINA::Euler), k_FixtureCEulerAligned);

  UnitTest::CheckArraysInheritTupleDims(dataStructure);
}

//------------------------------------------------------------------------------
// The pinned reader ignores the Format Version entirely -- its four version
// branches are empty and the dataset itself is optional. All three variants must
// produce the same output.
//------------------------------------------------------------------------------
TEST_CASE("OrientationAnalysis::ReadH5OinaDataFilter: Format Version Variants", "[OrientationAnalysis][ReadH5OinaDataFilter]")
{
  UnitTest::LoadPlugins();

  const auto variant = GENERATE(as<std::string>{}, "5.0", "2.0", "absent");

  DYNAMIC_SECTION("Format Version " << variant)
  {
    const fs::path inputFile = WriteH5OinaFixture(fmt::format("read_h5oina_vv_version_{}.h5oina", variant), {MakeFixtureAScan()}, variant != "absent", variant);

    ReadH5OinaDataFilter filter;
    DataStructure dataStructure;
    const Arguments args = MakeArgs(inputFile, {"1"});

    auto preflightResult = filter.preflight(dataStructure, args);
    SIMPLNX_RESULT_REQUIRE_VALID(preflightResult.outputActions);
    auto executeResult = filter.execute(dataStructure, args);
    SIMPLNX_RESULT_REQUIRE_VALID(executeResult.result);

    REQUIRE_NOTHROW(dataStructure.getDataRefAs<ImageGeom>(k_ImageGeomPath));
    REQUIRE(dataStructure.getDataRefAs<ImageGeom>(k_ImageGeomPath).getDimensions() == SizeVec3(3, 2, 1));
    CompareArrayValues<float32>(dataStructure, k_CellAMPath.createChildPath(ebsdlib::H5OINA::Euler), k_FixtureAEulerAligned);

    UnitTest::CheckArraysInheritTupleDims(dataStructure);
  }
}

//------------------------------------------------------------------------------
// Value-add preflight rejections that need no file at all.
//------------------------------------------------------------------------------
TEST_CASE("OrientationAnalysis::ReadH5OinaDataFilter: Parameter Rejections", "[OrientationAnalysis][ReadH5OinaDataFilter]")
{
  UnitTest::LoadPlugins();

  const fs::path inputFile = WriteH5OinaFixture("read_h5oina_vv_params.h5oina", {MakeFixtureAScan()});

  ReadH5OinaDataFilter filter;
  DataStructure dataStructure;
  Arguments args = MakeArgs(inputFile, {"1"});
  int32 expectedCode = 0;

  SECTION("Non-positive Z Spacing (-9580)")
  {
    args = MakeArgs(inputFile, {"1"}, 0.0F);
    expectedCode = -9580;
  }
  SECTION("No Scan Names Selected (-9581)")
  {
    args = MakeArgs(inputFile, {});
    expectedCode = -9581;
  }
  SECTION("Pattern Import Not Supported (-9583)")
  {
    args = MakeArgs(inputFile, {"1"}, 1.0F, true, true, true);
    expectedCode = -9583;
  }

  auto preflightResult = filter.preflight(dataStructure, args);
  SIMPLNX_RESULT_REQUIRE_INVALID(preflightResult.outputActions);
  REQUIRE(preflightResult.outputActions.errors()[0].code == expectedCode);

  auto executeResult = filter.execute(dataStructure, args);
  SIMPLNX_RESULT_REQUIRE_INVALID(executeResult.result);

  UnitTest::CheckArraysInheritTupleDims(dataStructure);
}

//------------------------------------------------------------------------------
// Value-add guard: a header whose cell counts are not usable is rejected before
// a zero-sized (or absurdly-sized) geometry is created.
//------------------------------------------------------------------------------
TEST_CASE("OrientationAnalysis::ReadH5OinaDataFilter: Invalid Cell Counts rejected (-9584)", "[OrientationAnalysis][ReadH5OinaDataFilter]")
{
  UnitTest::LoadPlugins();

  ScanSpec scan = MakeFixtureAScan();
  std::string fileName;

  SECTION("Zero X Cells")
  {
    scan.xCells = 0;
    fileName = "read_h5oina_vv_zero_xcells.h5oina";
  }
  SECTION("Zero Y Cells")
  {
    scan.yCells = 0;
    fileName = "read_h5oina_vv_zero_ycells.h5oina";
  }
  SECTION("Negative X Cells")
  {
    scan.xCells = -3;
    fileName = "read_h5oina_vv_negative_xcells.h5oina";
  }

  const fs::path inputFile = WriteH5OinaFixture(fileName, {scan});

  ReadH5OinaDataFilter filter;
  DataStructure dataStructure;
  const Arguments args = MakeArgs(inputFile, {"1"});

  auto preflightResult = filter.preflight(dataStructure, args);
  SIMPLNX_RESULT_REQUIRE_INVALID(preflightResult.outputActions);
  REQUIRE(preflightResult.outputActions.errors()[0].code == -9584);

  UnitTest::CheckArraysInheritTupleDims(dataStructure);
}

//------------------------------------------------------------------------------
// Value-add guard: the geometry is built from the FIRST selected scan's header,
// so every other selected scan has to agree with it. A second scan with a
// different grid is rejected at preflight rather than driving an out-of-bounds
// read of the reader's buffers at execute.
//------------------------------------------------------------------------------
TEST_CASE("OrientationAnalysis::ReadH5OinaDataFilter: Scan Header Mismatch rejected (-9585)", "[OrientationAnalysis][ReadH5OinaDataFilter]")
{
  UnitTest::LoadPlugins();

  ScanSpec scan2 = MakeFixtureBScan2();

  SECTION("Differing cell counts")
  {
    scan2.xCells = 3;
    scan2.yCells = 3;
    scan2.phase.assign(9, 1);
    scan2.bandContrast.assign(9, 7);
    scan2.bandSlope.assign(9, 7);
    scan2.bands.assign(9, 7);
    scan2.error.assign(9, 0);
    scan2.euler.assign(27, 0.5F);
    scan2.mad.assign(9, 0.25F);
    scan2.x.assign(9, 0.0F);
    scan2.y.assign(9, 0.0F);
  }
  SECTION("Differing step size")
  {
    scan2.xStep = 0.75F;
  }

  const fs::path inputFile = WriteH5OinaFixture("read_h5oina_vv_scan_mismatch.h5oina", {MakeFixtureBScan1(), scan2});

  ReadH5OinaDataFilter filter;
  DataStructure dataStructure;
  const Arguments args = MakeArgs(inputFile, {"1", "2"});

  auto preflightResult = filter.preflight(dataStructure, args);
  SIMPLNX_RESULT_REQUIRE_INVALID(preflightResult.outputActions);
  REQUIRE(preflightResult.outputActions.errors()[0].code == -9585);

  UnitTest::CheckArraysInheritTupleDims(dataStructure);
}

//------------------------------------------------------------------------------
// Value-add guard: every selected scan name is checked against the file at
// preflight, not just the first one. Without this a bad second name fails
// part-way through execute with half the arrays already populated.
//------------------------------------------------------------------------------
TEST_CASE("OrientationAnalysis::ReadH5OinaDataFilter: Missing Scan Name rejected (-9586)", "[OrientationAnalysis][ReadH5OinaDataFilter]")
{
  UnitTest::LoadPlugins();

  const fs::path inputFile = WriteH5OinaFixture("read_h5oina_vv_missing_scan.h5oina", {MakeFixtureBScan1(), MakeFixtureBScan2()});

  std::list<std::string> scanNames;
  SECTION("Missing first scan")
  {
    scanNames = {"9"};
  }
  SECTION("Missing second scan")
  {
    scanNames = {"1", "9"};
  }

  ReadH5OinaDataFilter filter;
  DataStructure dataStructure;
  const Arguments args = MakeArgs(inputFile, scanNames);

  auto preflightResult = filter.preflight(dataStructure, args);
  SIMPLNX_RESULT_REQUIRE_INVALID(preflightResult.outputActions);
  REQUIRE(preflightResult.outputActions.errors()[0].code == -9586);

  UnitTest::CheckArraysInheritTupleDims(dataStructure);
}

//------------------------------------------------------------------------------
// Value-add guard: phase indices come from the HDF5 phase GROUP NAMES, while the
// ensemble matrix is sized from the phase COUNT. A file whose groups are not
// numbered 1..N is rejected instead of writing past the end of the ensemble
// arrays.
//
// The ensemble fill in the shared IEbsdOemReader::readData runs once per SELECTED
// scan, so the check has to run for every selected scan and not only the first.
// The "Later selected scan" section is the same defect shape moved into scan "2":
// with the check applied to the first scan only, that file passes preflight and
// crashes the process at execute.
//------------------------------------------------------------------------------
TEST_CASE("OrientationAnalysis::ReadH5OinaDataFilter: Phase Index Out Of Range rejected (-9587)", "[OrientationAnalysis][ReadH5OinaDataFilter]")
{
  UnitTest::LoadPlugins();

  std::vector<ScanSpec> scans;
  std::list<std::string> scanNames;
  std::string fileName;

  SECTION("First selected scan")
  {
    ScanSpec scan = MakeFixtureBScan1();
    scan.phases[0].groupName = "7"; // one phase, but it claims index 7
    scans = {scan};
    scanNames = {"1"};
    fileName = "read_h5oina_vv_phase_index.h5oina";
  }
  SECTION("Later selected scan")
  {
    ScanSpec scan2 = MakeFixtureBScan2();
    scan2.phases[0].groupName = "7";
    scans = {MakeFixtureBScan1(), scan2};
    scanNames = {"1", "2"};
    fileName = "read_h5oina_vv_phase_index_scan2.h5oina";
  }

  const fs::path inputFile = WriteH5OinaFixture(fileName, scans);

  ReadH5OinaDataFilter filter;
  DataStructure dataStructure;
  const Arguments args = MakeArgs(inputFile, scanNames);

  auto preflightResult = filter.preflight(dataStructure, args);
  SIMPLNX_RESULT_REQUIRE_INVALID(preflightResult.outputActions);
  REQUIRE(preflightResult.outputActions.errors()[0].code == -9587);

  UnitTest::CheckArraysInheritTupleDims(dataStructure);
}

//------------------------------------------------------------------------------
// Value-add guard: the ensemble arrays are sized from the FIRST selected scan's
// phase count, and every selected scan fills them from its own phase groups. A
// later scan that declares more phase groups than the first therefore writes past
// the end of all three ensemble arrays, and a later scan that declares fewer
// silently leaves the first scan's phases in place under different definitions.
// Neither is a malformed file: different scans of a real multi-scan AZtec export
// may legitimately declare different phase lists.
//------------------------------------------------------------------------------
TEST_CASE("OrientationAnalysis::ReadH5OinaDataFilter: Scan Phase Count Mismatch rejected (-9589)", "[OrientationAnalysis][ReadH5OinaDataFilter]")
{
  UnitTest::LoadPlugins();

  ScanSpec scan1 = MakeFixtureBScan1();
  ScanSpec scan2 = MakeFixtureBScan2();
  std::string fileName;

  SECTION("Later scan declares more phases")
  {
    // Groups "1", "2" and "3" against the first scan's single group "1".
    scan2.phases = {k_CubicPhase, k_HexPhase, k_CubicPhase};
    fileName = "read_h5oina_vv_phase_count_more.h5oina";
  }
  SECTION("Later scan declares fewer phases")
  {
    scan1.phases = {k_CubicPhase, k_HexPhase};
    fileName = "read_h5oina_vv_phase_count_fewer.h5oina";
  }

  const fs::path inputFile = WriteH5OinaFixture(fileName, {scan1, scan2});

  ReadH5OinaDataFilter filter;
  DataStructure dataStructure;
  const Arguments args = MakeArgs(inputFile, {"1", "2"});

  auto preflightResult = filter.preflight(dataStructure, args);
  SIMPLNX_RESULT_REQUIRE_INVALID(preflightResult.outputActions);
  REQUIRE(preflightResult.outputActions.errors()[0].code == -9589);

  UnitTest::CheckArraysInheritTupleDims(dataStructure);
}

//------------------------------------------------------------------------------
// Value-add guard: EbsdLib sizes its data buffers to the ACTUAL dataset extent
// while the geometry is sized from the header's cell counts. A file whose Data
// datasets are shorter than X Cells * Y Cells is rejected before the copy spans
// past the end of those buffers.
//------------------------------------------------------------------------------
TEST_CASE("OrientationAnalysis::ReadH5OinaDataFilter: Dataset Extent Mismatch rejected (-34971)", "[OrientationAnalysis][ReadH5OinaDataFilter]")
{
  UnitTest::LoadPlugins();

  // Header declares a 4 x 4 = 16 point scan; the Data datasets hold 8 points.
  ScanSpec scan = MakeFixtureBScan1();
  scan.xCells = 4;
  scan.yCells = 4;
  scan.phase.assign(8, 1);
  scan.bandContrast.assign(8, 5);
  scan.bandSlope.assign(8, 6);
  scan.bands.assign(8, 7);
  scan.error.assign(8, 0);
  scan.euler.assign(24, 0.25F);
  scan.mad.assign(8, 0.125F);
  scan.x.assign(8, 0.0F);
  scan.y.assign(8, 0.0F);

  const fs::path inputFile = WriteH5OinaFixture("read_h5oina_vv_short_data.h5oina", {scan});

  ReadH5OinaDataFilter filter;
  DataStructure dataStructure;
  const Arguments args = MakeArgs(inputFile, {"1"});

  auto preflightResult = filter.preflight(dataStructure, args);
  SIMPLNX_RESULT_REQUIRE_VALID(preflightResult.outputActions);

  auto executeResult = filter.execute(dataStructure, args);
  SIMPLNX_RESULT_REQUIRE_INVALID(executeResult.result);
  REQUIRE(executeResult.result.errors()[0].code == -34971);

  UnitTest::CheckArraysInheritTupleDims(dataStructure);
}

//------------------------------------------------------------------------------
// Value-add guard: a Phase byte larger than the file's phase count would index
// past the end of the CrystalStructures array in the alignment loop.
//------------------------------------------------------------------------------
TEST_CASE("OrientationAnalysis::ReadH5OinaDataFilter: Out-of-Range Phase Value rejected (-34972)", "[OrientationAnalysis][ReadH5OinaDataFilter]")
{
  UnitTest::LoadPlugins();

  // One phase in the header, so the valid Phase range is [0, 1]; point 2 carries 5.
  ScanSpec scan = MakeFixtureBScan1();
  scan.phase = {1, 1, 5, 1};

  const fs::path inputFile = WriteH5OinaFixture("read_h5oina_vv_phase_range.h5oina", {scan});

  ReadH5OinaDataFilter filter;
  DataStructure dataStructure;
  const Arguments args = MakeArgs(inputFile, {"1"});

  auto preflightResult = filter.preflight(dataStructure, args);
  SIMPLNX_RESULT_REQUIRE_VALID(preflightResult.outputActions);

  auto executeResult = filter.execute(dataStructure, args);
  SIMPLNX_RESULT_REQUIRE_INVALID(executeResult.result);
  REQUIRE(executeResult.result.errors()[0].code == -34972);

  UnitTest::CheckArraysInheritTupleDims(dataStructure);
}

//------------------------------------------------------------------------------
// Error propagation from the trusted EbsdLib boundary. A Data group missing one
// of the nine required datasets is fatal inside H5OINAReader::readData; the
// filter surfaces it as -8970 with the reader's own code and message attached.
//------------------------------------------------------------------------------
TEST_CASE("OrientationAnalysis::ReadH5OinaDataFilter: EbsdLib Error Passthrough - Missing Data Column (-8970)", "[OrientationAnalysis][ReadH5OinaDataFilter]")
{
  UnitTest::LoadPlugins();

  ScanSpec scan = MakeFixtureAScan();
  scan.omitBandsDataset = true;

  const fs::path inputFile = WriteH5OinaFixture("read_h5oina_vv_missing_bands.h5oina", {scan});

  ReadH5OinaDataFilter filter;
  DataStructure dataStructure;
  const Arguments args = MakeArgs(inputFile, {"1"});

  // The Data datasets are only read at execute, so preflight (header only) succeeds.
  auto preflightResult = filter.preflight(dataStructure, args);
  SIMPLNX_RESULT_REQUIRE_VALID(preflightResult.outputActions);

  auto executeResult = filter.execute(dataStructure, args);
  SIMPLNX_RESULT_REQUIRE_INVALID(executeResult.result);
  REQUIRE(executeResult.result.errors()[0].code == -8970);
  // The message names the scan and the file so the user can find the problem.
  REQUIRE(executeResult.result.errors()[0].message.find("'1'") != std::string::npos);
  REQUIRE(executeResult.result.errors()[0].message.find(inputFile.filename().string()) != std::string::npos);

  UnitTest::CheckArraysInheritTupleDims(dataStructure);
}

//------------------------------------------------------------------------------
// Error propagation from the trusted EbsdLib boundary at header-read time: a
// phase group missing its Lattice Angles dataset is reported through -9582, and
// the message carries the file path and scan name.
//
// The header of every selected scan is read at preflight, from two different
// return sites: the first selected scan's read and the per-scan loop's read. Both
// are pinned here, and each section asserts the scan name its own site injects.
//------------------------------------------------------------------------------
TEST_CASE("OrientationAnalysis::ReadH5OinaDataFilter: EbsdLib Error Passthrough - Missing Lattice Angles (-9582)", "[OrientationAnalysis][ReadH5OinaDataFilter]")
{
  UnitTest::LoadPlugins();

  std::vector<ScanSpec> scans;
  std::list<std::string> scanNames;
  std::string fileName;
  std::string expectedScanName;

  SECTION("First selected scan")
  {
    ScanSpec scan = MakeFixtureAScan();
    scan.phases[0].omitLatticeAngles = true;
    scans = {scan};
    scanNames = {"1"};
    fileName = "read_h5oina_vv_missing_angles.h5oina";
    expectedScanName = "'1'";
  }
  SECTION("Later selected scan")
  {
    ScanSpec scan2 = MakeFixtureBScan2();
    scan2.phases[0].omitLatticeAngles = true;
    scans = {MakeFixtureBScan1(), scan2};
    scanNames = {"1", "2"};
    fileName = "read_h5oina_vv_missing_angles_scan2.h5oina";
    expectedScanName = "'2'";
  }

  const fs::path inputFile = WriteH5OinaFixture(fileName, scans);

  ReadH5OinaDataFilter filter;
  DataStructure dataStructure;
  const Arguments args = MakeArgs(inputFile, scanNames);

  auto preflightResult = filter.preflight(dataStructure, args);
  SIMPLNX_RESULT_REQUIRE_INVALID(preflightResult.outputActions);
  REQUIRE(preflightResult.outputActions.errors()[0].code == -9582);
  REQUIRE(preflightResult.outputActions.errors()[0].message.find(inputFile.filename().string()) != std::string::npos);
  REQUIRE(preflightResult.outputActions.errors()[0].message.find(expectedScanName) != std::string::npos);

  UnitTest::CheckArraysInheritTupleDims(dataStructure);
}

//------------------------------------------------------------------------------
// The scan-selection parameter carries a stacking order that this filter does
// not act on: scans are always stacked in the order they appear in the list.
// Selecting High-to-Low therefore raises a preflight warning rather than
// silently accepting a setting that has no effect.
//------------------------------------------------------------------------------
TEST_CASE("OrientationAnalysis::ReadH5OinaDataFilter: Stacking Order Warning (-9588)", "[OrientationAnalysis][ReadH5OinaDataFilter]")
{
  UnitTest::LoadPlugins();

  const fs::path inputFile = WriteH5OinaFixture("read_h5oina_vv_stacking.h5oina", {MakeFixtureBScan1(), MakeFixtureBScan2()});

  ReadH5OinaDataFilter filter;

  {
    DataStructure dataStructure;
    const Arguments args = MakeArgs(inputFile, {"1", "2"}, 1.0F, true, true, false, RefFrameZDir::k_HightoLow);
    auto preflightResult = filter.preflight(dataStructure, args);
    SIMPLNX_RESULT_REQUIRE_VALID(preflightResult.outputActions);
    REQUIRE(preflightResult.outputActions.warnings().size() == 1);
    REQUIRE(preflightResult.outputActions.warnings()[0].code == -9588);
  }
  {
    DataStructure dataStructure;
    const Arguments args = MakeArgs(inputFile, {"1", "2"}, 1.0F, true, true, false, RefFrameZDir::k_LowtoHigh);
    auto preflightResult = filter.preflight(dataStructure, args);
    SIMPLNX_RESULT_REQUIRE_VALID(preflightResult.outputActions);
    REQUIRE(preflightResult.outputActions.warnings().empty());
  }
}

//------------------------------------------------------------------------------
// Class 2 independent readback against the archived production AZtec file.
//
// The expected cell values are read straight out of the .h5oina's own Data
// datasets with H5Lite, bypassing H5OINAReader, and the ensemble expectations are
// derived from the file's phase group (Laue 11 -> Cubic_High; lattice angles
// pi/2 radians -> 90 degrees). The archive's H5Oina_Test_Data.dream3d exemplar is
// deliberately NOT consulted -- it was written by this filter and would only pin
// the filter against itself.
//
// This file is a single 25 x 25 cubic scan, so it exercises the single-scan copy
// plumbing, the Phase widening (its Phase column contains both 0 and 1) and the
// ensemble fill on production data. It cannot exercise the hexagonal alignment or
// the multi-scan slab offsets; the toy fixtures above carry those.
//------------------------------------------------------------------------------
TEST_CASE("OrientationAnalysis::ReadH5OinaDataFilter: Real AZtec File Readback", "[OrientationAnalysis][ReadH5OinaDataFilter]")
{
  UnitTest::LoadPlugins();

  const nx::core::UnitTest::TestFileSentinel testDataSentinel(nx::core::unit_test::k_TestFilesDir, "H5Oina_Test_Data.tar.gz", "H5Oina_Test_Data");

  const fs::path inputFile = fs::path(fmt::format("{}/H5Oina_Test_Data/H5Oina_Test_Data.h5oina", unit_test::k_TestFilesDir));
  REQUIRE(fs::exists(inputFile));

  ReadH5OinaDataFilter filter;
  DataStructure dataStructure;
  const Arguments args = MakeArgs(inputFile, {"1"});

  auto preflightResult = filter.preflight(dataStructure, args);
  SIMPLNX_RESULT_REQUIRE_VALID(preflightResult.outputActions);
  auto executeResult = filter.execute(dataStructure, args);
  SIMPLNX_RESULT_REQUIRE_VALID(executeResult.result);

  // Geometry: X Cells = Y Cells = 25, X Step = Y Step = 4.0, one scan selected.
  REQUIRE_NOTHROW(dataStructure.getDataRefAs<ImageGeom>(k_ImageGeomPath));
  const auto& imageGeom = dataStructure.getDataRefAs<ImageGeom>(k_ImageGeomPath);
  REQUIRE(imageGeom.getDimensions() == SizeVec3(25, 25, 1));
  REQUIRE(imageGeom.getSpacing() == FloatVec3(4.0F, 4.0F, 1.0F));
  REQUIRE(imageGeom.getOrigin() == FloatVec3(0.0F, 0.0F, 0.0F));
  REQUIRE(imageGeom.getUnits() == IGeometry::LengthUnit::Micrometer);

  // Every cell array is a verbatim copy of the corresponding Data dataset: this
  // scan's only phase is Laue 11 (Cubic_High), so no point takes the alignment.
  const std::string dataPrefix = fmt::format("/1/{}/{}/", ebsdlib::H5OINA::EBSD, ebsdlib::H5OINA::Data);
  CompareArrayValues<uint8>(dataStructure, k_CellAMPath.createChildPath(ebsdlib::H5OINA::BandContrast), ReadRawDataset<uint8>(inputFile, dataPrefix + ebsdlib::H5OINA::BandContrast));
  CompareArrayValues<uint8>(dataStructure, k_CellAMPath.createChildPath(ebsdlib::H5OINA::BandSlope), ReadRawDataset<uint8>(inputFile, dataPrefix + ebsdlib::H5OINA::BandSlope));
  CompareArrayValues<uint8>(dataStructure, k_CellAMPath.createChildPath(ebsdlib::H5OINA::Bands), ReadRawDataset<uint8>(inputFile, dataPrefix + ebsdlib::H5OINA::Bands));
  CompareArrayValues<uint8>(dataStructure, k_CellAMPath.createChildPath(ebsdlib::H5OINA::Error), ReadRawDataset<uint8>(inputFile, dataPrefix + ebsdlib::H5OINA::Error));
  CompareArrayValues<float32>(dataStructure, k_CellAMPath.createChildPath(ebsdlib::H5OINA::Euler), ReadRawDataset<float32>(inputFile, dataPrefix + ebsdlib::H5OINA::Euler));
  CompareArrayValues<float32>(dataStructure, k_CellAMPath.createChildPath(ebsdlib::H5OINA::MeanAngularDeviation),
                              ReadRawDataset<float32>(inputFile, dataPrefix + ebsdlib::H5OINA::MeanAngularDeviation));
  CompareArrayValues<float32>(dataStructure, k_CellAMPath.createChildPath(ebsdlib::H5OINA::X), ReadRawDataset<float32>(inputFile, dataPrefix + ebsdlib::H5OINA::X));
  CompareArrayValues<float32>(dataStructure, k_CellAMPath.createChildPath(ebsdlib::H5OINA::Y), ReadRawDataset<float32>(inputFile, dataPrefix + ebsdlib::H5OINA::Y));

  // Phase is the file's uint8 column widened to int32.
  {
    const std::vector<uint8> rawPhase = ReadRawDataset<uint8>(inputFile, dataPrefix + ebsdlib::H5OINA::Phase);
    std::vector<int32> expectedPhase(rawPhase.size());
    for(usize i = 0; i < rawPhase.size(); i++)
    {
      expectedPhase[i] = static_cast<int32>(rawPhase[i]);
    }
    CompareArrayValues<int32>(dataStructure, k_CellAMPath.createChildPath(ebsdlib::H5OINA::Phase), expectedPhase);
  }

  // Ensemble: slot 0 is the reserved Invalid Phase; slot 1 is the file's single
  // "Titanium cubic" phase, Laue group 11 -> Cubic_High, lattice dimensions
  // 3.192 and lattice angles pi/2 radians stored as 90 degrees.
  CompareArrayValues<uint32>(dataStructure, k_EnsembleAMPath.createChildPath(ebsdlib::AngFile::CrystalStructures),
                             {ebsdlib::CrystalStructure::UnknownCrystalStructure, ebsdlib::CrystalStructure::Cubic_High});
  CompareStringArrayValues(dataStructure, k_EnsembleAMPath.createChildPath(ebsdlib::AngFile::MaterialName), {"Invalid Phase", "Titanium cubic"});
  CompareArrayValues<float32>(dataStructure, k_EnsembleAMPath.createChildPath(ebsdlib::AngFile::LatticeConstants),
                              {
                                  0.0F,
                                  0.0F,
                                  0.0F,
                                  0.0F,
                                  0.0F,
                                  0.0F,
                                  3.192F,
                                  3.192F,
                                  3.192F,
                                  90.0F,
                                  90.0F,
                                  90.0F,
                              });

  UnitTest::CheckArraysInheritTupleDims(dataStructure);
}
