#include "WriteDAMASKFiles.hpp"

#include "simplnx/Common/AtomicFile.hpp"
#include "simplnx/DataStructure/DataArray.hpp"
#include "simplnx/DataStructure/Geometry/ImageGeom.hpp"
#include "simplnx/Utilities/MessageHelper.hpp"

#include <fmt/format.h>

#include <algorithm>
#include <array>
#include <filesystem>
#include <fstream>
#include <iterator>
#include <numbers>
#include <string>
#include <string_view>
#include <vector>

namespace fs = std::filesystem;
using namespace nx::core;

namespace
{
enum class WriteStatus
{
  Success,
  Cancelled,
  OpenError,
  WriteError
};

enum class FileIndex : usize
{
  Geometry = 0,
  Material = 1
};

struct GrainData
{
  std::vector<int32> Phases;
  std::vector<std::array<float32, 3>> Orientations;
  std::vector<bool> HasCells;
};

constexpr usize ToIndex(FileIndex fileIndex)
{
  return static_cast<usize>(fileIndex);
}

WriteStatus FlushBuffer(std::ostream& output, fmt::memory_buffer& buffer)
{
  output.write(buffer.data(), static_cast<std::streamsize>(buffer.size()));
  buffer.clear();
  return output ? WriteStatus::Success : WriteStatus::WriteError;
}

WriteStatus CloseOutput(std::ofstream& output)
{
  output.close();
  return output ? WriteStatus::Success : WriteStatus::WriteError;
}

void SendProgress(ThrottledMessenger& messenger, std::string_view label, usize current, usize total)
{
  messenger.sendThrottledMessage([=]() { return fmt::format("{}: {:.0f}%", label, CalculatePercentComplete(current, total)); });
}

void WriteGeometryHeader(fmt::memory_buffer& buffer, const ImageGeom& imageGeom, int32 homogenizationIndex, usize microstructureCount)
{
  const auto dimensions = imageGeom.getDimensions();
  const auto spacing = imageGeom.getSpacing();
  const auto origin = imageGeom.getOrigin();
  const std::array<float32, 3> size = {static_cast<float32>(dimensions[0]) * spacing[0], static_cast<float32>(dimensions[1]) * spacing[1], static_cast<float32>(dimensions[2]) * spacing[2]};

  fmt::format_to(std::back_inserter(buffer), "6       header\n");
  fmt::format_to(std::back_inserter(buffer), "# Generated by DREAM.3D\n");
  fmt::format_to(std::back_inserter(buffer), "grid    a {}    b {}    c {}\n", dimensions[0], dimensions[1], dimensions[2]);
  fmt::format_to(std::back_inserter(buffer), "size    x {:.3f}    y {:.3f}    z {:.3f}\n", size[0], size[1], size[2]);
  fmt::format_to(std::back_inserter(buffer), "origin    x {:.3f}    y {:.3f}    z {:.3f}\n", origin[0], origin[1], origin[2]);
  fmt::format_to(std::back_inserter(buffer), "homogenization  {}\n", homogenizationIndex);
  fmt::format_to(std::back_inserter(buffer), "microstructures {}\n", microstructureCount);
}

WriteStatus WriteGeometryFile(const fs::path& filePath, const ImageGeom& imageGeom, const AbstractDataStore<int32>& featureIds, const WriteDAMASKFilesInputValues& inputValues,
                              usize microstructureCount, const std::atomic_bool& shouldCancel, MessageHelper& messageHelper)
{
  std::ofstream output(filePath, std::ios::binary);
  if(!output.is_open())
  {
    return WriteStatus::OpenError;
  }

  fmt::memory_buffer buffer;
  WriteGeometryHeader(buffer, imageGeom, inputValues.HomogenizationIndex, microstructureCount);
  const usize cellCount = imageGeom.getNumberOfCells();
  if(inputValues.DataFormat == 0 && inputValues.CompressGeomFile)
  {
    if(shouldCancel)
    {
      return WriteStatus::Cancelled;
    }
    fmt::format_to(std::back_inserter(buffer), "1 to {:10d}", cellCount);
    if(FlushBuffer(output, buffer) == WriteStatus::WriteError)
    {
      return WriteStatus::WriteError;
    }
    return CloseOutput(output);
  }

  const auto dimensions = imageGeom.getDimensions();
  const usize cellsPerSlice = dimensions[0] * dimensions[1];
  usize entriesPerLine = 0;
  ThrottledMessenger progressMessenger = messageHelper.createThrottledMessenger();
  for(usize z = 0; z < dimensions[2]; z++)
  {
    if(shouldCancel)
    {
      return WriteStatus::Cancelled;
    }

    const usize sliceStart = z * cellsPerSlice;
    const usize sliceEnd = sliceStart + cellsPerSlice;
    for(usize cellIndex = sliceStart; cellIndex < sliceEnd; cellIndex++)
    {
      if(entriesPerLine != 0)
      {
        // This modulo check mirrors the legacy counter for parity.
        if(entriesPerLine % dimensions[0] != 0)
        {
          fmt::format_to(std::back_inserter(buffer), " ");
        }
        else
        {
          fmt::format_to(std::back_inserter(buffer), "\n");
          entriesPerLine = 0;
        }
      }

      const int64 value = inputValues.DataFormat == 0 ? static_cast<int64>(cellIndex + 1) : static_cast<int64>(featureIds[cellIndex]);
      fmt::format_to(std::back_inserter(buffer), "{:10d}", value);
      entriesPerLine++;
    }

    if(FlushBuffer(output, buffer) == WriteStatus::WriteError)
    {
      return WriteStatus::WriteError;
    }
    SendProgress(progressMessenger, "Writing Geometry File (File 1/2)", z + 1, dimensions[2]);
  }

  if(buffer.size() != 0 && FlushBuffer(output, buffer) == WriteStatus::WriteError)
  {
    return WriteStatus::WriteError;
  }
  return CloseOutput(output);
}

void WriteMaterialHeader(fmt::memory_buffer& buffer)
{
  fmt::format_to(std::back_inserter(buffer), "#############################################################################\n");
  fmt::format_to(std::back_inserter(buffer), "# Generated by DREAM.3D\n");
  fmt::format_to(std::back_inserter(buffer), "#############################################################################\n");
  fmt::format_to(std::back_inserter(buffer), "# Add <homogenization>, <crystallite>, and <phase> for a complete definition\n");
  fmt::format_to(std::back_inserter(buffer), "#############################################################################\n");
}

void WriteTexture(fmt::memory_buffer& buffer, std::string_view label, usize index, const std::array<float32, 3>& orientation)
{
  constexpr float64 k_RadiansToDegrees = 180.0 / std::numbers::pi;
  const float64 phi1 = static_cast<float64>(orientation[0]) * k_RadiansToDegrees;
  const float64 phi = static_cast<float64>(orientation[1]) * k_RadiansToDegrees;
  const float64 phi2 = static_cast<float64>(orientation[2]) * k_RadiansToDegrees;
  fmt::format_to(std::back_inserter(buffer), "[{}{}]\n", label, index);
  fmt::format_to(std::back_inserter(buffer), "(gauss) phi1 {:.3f}   Phi {:.3f}    phi2 {:.3f}   scatter 0.0   fraction 1.0 \n", phi1, phi, phi2);
}

void WriteMicrostructure(fmt::memory_buffer& buffer, std::string_view label, usize index, int32 phase)
{
  fmt::format_to(std::back_inserter(buffer), "[{}{}]\n", label, index);
  fmt::format_to(std::back_inserter(buffer), "crystallite 1\n");
  fmt::format_to(std::back_inserter(buffer), "(constituent)   phase {} texture {} fraction 1.0\n", phase, index);
}

WriteStatus WritePointwiseMaterial(std::ofstream& output, fmt::memory_buffer& buffer, const ImageGeom& imageGeom, const AbstractDataStore<float32>& cellEulerAngles,
                                   const AbstractDataStore<int32>& cellPhases, const std::atomic_bool& shouldCancel, MessageHelper& messageHelper)
{
  const auto dimensions = imageGeom.getDimensions();
  const usize cellsPerSlice = dimensions[0] * dimensions[1];
  const usize progressTotal = dimensions[2] * 2;
  ThrottledMessenger progressMessenger = messageHelper.createThrottledMessenger();

  fmt::format_to(std::back_inserter(buffer), "<texture>\n");
  for(usize z = 0; z < dimensions[2]; z++)
  {
    if(shouldCancel)
    {
      return WriteStatus::Cancelled;
    }
    const usize sliceStart = z * cellsPerSlice;
    const usize sliceEnd = sliceStart + cellsPerSlice;
    for(usize cellIndex = sliceStart; cellIndex < sliceEnd; cellIndex++)
    {
      const std::array<float32, 3> orientation = {cellEulerAngles[cellIndex * 3], cellEulerAngles[cellIndex * 3 + 1], cellEulerAngles[cellIndex * 3 + 2]};
      WriteTexture(buffer, "point", cellIndex + 1, orientation);
    }
    if(FlushBuffer(output, buffer) == WriteStatus::WriteError)
    {
      return WriteStatus::WriteError;
    }
    SendProgress(progressMessenger, "Writing Material Configuration (File 2/2)", z + 1, progressTotal);
  }

  fmt::format_to(std::back_inserter(buffer), "<microstructure>\n");
  for(usize z = 0; z < dimensions[2]; z++)
  {
    if(shouldCancel)
    {
      return WriteStatus::Cancelled;
    }
    const usize sliceStart = z * cellsPerSlice;
    const usize sliceEnd = sliceStart + cellsPerSlice;
    for(usize cellIndex = sliceStart; cellIndex < sliceEnd; cellIndex++)
    {
      WriteMicrostructure(buffer, "point", cellIndex + 1, cellPhases[cellIndex]);
    }
    if(FlushBuffer(output, buffer) == WriteStatus::WriteError)
    {
      return WriteStatus::WriteError;
    }
    SendProgress(progressMessenger, "Writing Material Configuration (File 2/2)", dimensions[2] + z + 1, progressTotal);
  }
  return WriteStatus::Success;
}

WriteStatus WriteGrainwiseMaterial(std::ofstream& output, fmt::memory_buffer& buffer, const GrainData& grainData, const std::atomic_bool& shouldCancel, MessageHelper& messageHelper)
{
  const usize grainCount = grainData.Phases.size() - 1;
  const usize progressTotal = grainCount * 2;
  ThrottledMessenger progressMessenger = messageHelper.createThrottledMessenger();

  fmt::format_to(std::back_inserter(buffer), "<texture>\n");
  for(usize grainId = 1; grainId <= grainCount; grainId++)
  {
    if(shouldCancel)
    {
      return WriteStatus::Cancelled;
    }
    WriteTexture(buffer, "grain", grainId, grainData.Orientations[grainId]);
    if(FlushBuffer(output, buffer) == WriteStatus::WriteError)
    {
      return WriteStatus::WriteError;
    }
    SendProgress(progressMessenger, "Writing Material Configuration (File 2/2)", grainId, progressTotal);
  }

  fmt::format_to(std::back_inserter(buffer), "<microstructure>\n");
  for(usize grainId = 1; grainId <= grainCount; grainId++)
  {
    if(shouldCancel)
    {
      return WriteStatus::Cancelled;
    }
    WriteMicrostructure(buffer, "grain", grainId, grainData.Phases[grainId]);
    if(FlushBuffer(output, buffer) == WriteStatus::WriteError)
    {
      return WriteStatus::WriteError;
    }
    SendProgress(progressMessenger, "Writing Material Configuration (File 2/2)", grainCount + grainId, progressTotal);
  }
  return WriteStatus::Success;
}

WriteStatus WriteMaterialFile(const fs::path& filePath, const ImageGeom& imageGeom, const AbstractDataStore<float32>& cellEulerAngles, const AbstractDataStore<int32>& cellPhases,
                              const WriteDAMASKFilesInputValues& inputValues, const GrainData& grainData, const std::atomic_bool& shouldCancel, MessageHelper& messageHelper)
{
  std::ofstream output(filePath, std::ios::binary);
  if(!output.is_open())
  {
    return WriteStatus::OpenError;
  }

  fmt::memory_buffer buffer;
  WriteMaterialHeader(buffer);
  const WriteStatus status = inputValues.DataFormat == 0 ? WritePointwiseMaterial(output, buffer, imageGeom, cellEulerAngles, cellPhases, shouldCancel, messageHelper) :
                                                           WriteGrainwiseMaterial(output, buffer, grainData, shouldCancel, messageHelper);
  if(status != WriteStatus::Success)
  {
    return status;
  }
  if(buffer.size() != 0 && FlushBuffer(output, buffer) == WriteStatus::WriteError)
  {
    return WriteStatus::WriteError;
  }
  return CloseOutput(output);
}

void RemoveTemporaryFiles(const std::vector<Result<AtomicFile>>& files)
{
  for(const auto& file : files)
  {
    if(file.valid())
    {
      file.value().removeTempFile();
    }
  }
}
} // namespace

WriteDAMASKFiles::WriteDAMASKFiles(DataStructure& dataStructure, const IFilter::MessageHandler& messageHandler, const std::atomic_bool& shouldCancel, WriteDAMASKFilesInputValues* inputValues)
: m_DataStructure(dataStructure)
, m_InputValues(inputValues)
, m_ShouldCancel(shouldCancel)
, m_MessageHandler(messageHandler)
{
}

WriteDAMASKFiles::~WriteDAMASKFiles() noexcept = default;

Result<> WriteDAMASKFiles::operator()()
{
  const auto& imageGeom = m_DataStructure.getDataRefAs<ImageGeom>(m_InputValues->ImageGeometryPath);
  const auto& featureIds = m_DataStructure.getDataRefAs<Int32Array>(m_InputValues->FeatureIdsArrayPath).getDataStoreRef();
  const auto& cellEulerAngles = m_DataStructure.getDataRefAs<Float32Array>(m_InputValues->CellEulerAnglesArrayPath).getDataStoreRef();
  const auto& cellPhases = m_DataStructure.getDataRefAs<Int32Array>(m_InputValues->CellPhasesArrayPath).getDataStoreRef();
  const auto dimensions = imageGeom.getDimensions();
  const usize cellsPerSlice = dimensions[0] * dimensions[1];
  MessageHelper messageHelper(m_MessageHandler);

  int32 maxGrainId = 0;
  GrainData grainData;
  if(m_InputValues->DataFormat == 1)
  {
    ThrottledMessenger maximumMessenger = messageHelper.createThrottledMessenger();
    for(usize z = 0; z < dimensions[2]; z++)
    {
      if(m_ShouldCancel)
      {
        return {};
      }
      const usize sliceStart = z * cellsPerSlice;
      const usize sliceEnd = sliceStart + cellsPerSlice;
      for(usize cellIndex = sliceStart; cellIndex < sliceEnd; cellIndex++)
      {
        const int32 featureId = featureIds[cellIndex];
        maxGrainId = std::max(maxGrainId, featureId);
      }
      SendProgress(maximumMessenger, "Finding Maximum Grain ID", z + 1, dimensions[2]);
    }

    if(maxGrainId <= 0)
    {
      return MakeErrorResult(
          -12074, fmt::format("The feature IDs array '{}' has no positive feature IDs. Grainwise DAMASK output requires at least one grain.", m_InputValues->FeatureIdsArrayPath.toString()));
    }

    const usize grainCount = static_cast<usize>(maxGrainId);
    grainData.Phases.resize(grainCount + 1, 0);
    grainData.Orientations.resize(grainCount + 1, {0.0F, 0.0F, 0.0F});
    grainData.HasCells.resize(grainCount + 1, false);

    // The direct-indexed buckets use 16 bytes per grain for phase and orientation. Presence flags use one bit per grain, with no per-cell temporary storage.
    ThrottledMessenger bucketMessenger = messageHelper.createThrottledMessenger();
    for(usize z = 0; z < dimensions[2]; z++)
    {
      if(m_ShouldCancel)
      {
        return {};
      }
      const usize sliceStart = z * cellsPerSlice;
      const usize sliceEnd = sliceStart + cellsPerSlice;
      for(usize cellIndex = sliceStart; cellIndex < sliceEnd; cellIndex++)
      {
        const int32 featureId = featureIds[cellIndex];
        if(featureId > 0)
        {
          const usize grainId = static_cast<usize>(featureId);
          grainData.HasCells[grainId] = true;
          grainData.Phases[grainId] = cellPhases[cellIndex];
          grainData.Orientations[grainId] = {cellEulerAngles[cellIndex * 3], cellEulerAngles[cellIndex * 3 + 1], cellEulerAngles[cellIndex * 3 + 2]};
        }
      }
      SendProgress(bucketMessenger, "Bucketing Grain Data", z + 1, dimensions[2]);
    }

    const usize emptyGrainCount = static_cast<usize>(std::count(grainData.HasCells.cbegin() + 1, grainData.HasCells.cend(), false));
    if(emptyGrainCount > 0)
    {
      m_MessageHandler(IFilter::Message::Type::Warning, fmt::format("{} grain{} in [1, {}] {} no cells. Phase 0 and zero Euler angles were written for the missing grain data.", emptyGrainCount,
                                                                    emptyGrainCount == 1 ? "" : "s", maxGrainId, emptyGrainCount == 1 ? "has" : "have"));
    }
  }

  const usize microstructureCount = m_InputValues->DataFormat == 0 ? imageGeom.getNumberOfCells() : static_cast<usize>(maxGrainId);
  const std::array<fs::path, 2> fileList = {m_InputValues->OutputPath / fmt::format("{}.geom", m_InputValues->GeometryFileName), m_InputValues->OutputPath / "material.config"};
  std::vector<Result<AtomicFile>> files;
  files.reserve(fileList.size());
  for(const auto& outputPath : fileList)
  {
    files.push_back(AtomicFile::Create(outputPath));
    if(files.back().invalid())
    {
      RemoveTemporaryFiles(files);
      return ConvertResult(std::move(files.back()));
    }
  }

  const auto writeFile = [&](FileIndex fileIndex, std::string_view progressMessage, auto&& writer) -> Result<> {
    if(m_ShouldCancel)
    {
      RemoveTemporaryFiles(files);
      return {};
    }

    messageHelper.sendMessage(std::string(progressMessage));
    const usize index = ToIndex(fileIndex);
    const fs::path tempPath = files[index].value().tempFilePath();
    const WriteStatus status = writer(tempPath);
    if(status == WriteStatus::Cancelled || m_ShouldCancel)
    {
      RemoveTemporaryFiles(files);
      return {};
    }
    if(status == WriteStatus::OpenError)
    {
      RemoveTemporaryFiles(files);
      return MakeErrorResult(-12075, fmt::format("Could not open '{}' for writing (target '{}').", tempPath.string(), fileList[index].string()));
    }
    if(status == WriteStatus::WriteError)
    {
      RemoveTemporaryFiles(files);
      return MakeErrorResult(-12076, fmt::format("Writing to '{}' failed (target '{}'). Check available disk space.", tempPath.string(), fileList[index].string()));
    }
    return {};
  };

  Result<> writeResult = writeFile(FileIndex::Geometry, "Writing Geometry File (File 1/2)...",
                                   [&](const fs::path& path) { return WriteGeometryFile(path, imageGeom, featureIds, *m_InputValues, microstructureCount, m_ShouldCancel, messageHelper); });
  if(writeResult.invalid())
  {
    return writeResult;
  }

  writeResult = writeFile(FileIndex::Material, "Writing Material Configuration (File 2/2)...",
                          [&](const fs::path& path) { return WriteMaterialFile(path, imageGeom, cellEulerAngles, cellPhases, *m_InputValues, grainData, m_ShouldCancel, messageHelper); });
  if(writeResult.invalid())
  {
    return writeResult;
  }

  if(m_ShouldCancel)
  {
    RemoveTemporaryFiles(files);
    return {};
  }

  for(auto& file : files)
  {
    Result<> commitResult = file.value().commit();
    if(commitResult.invalid())
    {
      RemoveTemporaryFiles(files);
      return commitResult;
    }
  }
  return {};
}
