cmake_minimum_required(VERSION 3.26)

foreach(required NXRUNNER_EXECUTABLE DEFAULTS_PROBE PIPELINE_FILE)
  if(NOT DEFINED ${required} OR NOT EXISTS "${${required}}")
    message(FATAL_ERROR "${required} was not supplied as an existing path")
  endif()
endforeach()
if(NOT DEFINED P1_ROOT_BASE OR "${P1_ROOT_BASE}" STREQUAL "" OR NOT IS_ABSOLUTE "${P1_ROOT_BASE}")
  message(FATAL_ERROR "P1_ROOT_BASE must be supplied as a nonempty absolute path; the directory need not exist")
endif()
include("${CMAKE_CURRENT_LIST_DIR}/OocProcessExitStatus.cmake")

execute_process(COMMAND "${DEFAULTS_PROBE}" RESULT_VARIABLE probe_status OUTPUT_VARIABLE defaults_output TIMEOUT 30)
if(NOT probe_status STREQUAL "0")
  message(FATAL_ERROR "The local Preferences default probe failed: ${probe_status}")
endif()
string(REGEX MATCHALL "[0-9]+" defaults "${defaults_output}")
list(LENGTH defaults default_count)
if(NOT default_count EQUAL 2)
  message(FATAL_ERROR "The local Preferences default probe did not return exactly two byte counts: ${defaults_output}")
endif()
list(GET defaults 0 array_default)
list(GET defaults 1 structure_default)
set(expected_array_line "Warning -591: Preferences: saved Large Data Size ('large_data_size') value -1 (JSON type number_integer) is invalid. Allowed domain: 0 to 18446744073709551615 bytes. Using the default: ${array_default} bytes. Review this value in Preferences > Out of Core.")
set(expected_structure_line "Warning -591: Preferences: saved Large Data Structure Size ('large_datastructure_size') value \"bad\" (JSON type string) is invalid. Allowed domain: 0 to 18446744073709551615 bytes. Using the default: ${structure_default} bytes. Review this value in Preferences > Out of Core.")

file(READ "${PIPELINE_FILE}" pipeline_template)
string(JSON source_format GET "${pipeline_template}" pipeline 1 args data_format value)
if(NOT source_format STREQUAL "HDF5-OOC")
  message(FATAL_ERROR "The preflight fixture's pipeline[1].args.data_format.value changed")
endif()
string(REGEX MATCHALL "\"value\"[ \t]*:[ \t]*\"HDF5-OOC\"" format_tokens "${pipeline_template}")
list(LENGTH format_tokens format_count)
if(NOT format_count EQUAL 1)
  message(FATAL_ERROR "The preflight fixture does not have one exact format token")
endif()
string(REPLACE "\"value\": \"HDF5-OOC\"" "\"value\": \"\"" pipeline "${pipeline_template}")
string(JSON selected_format GET "${pipeline}" pipeline 1 args data_format value)
if(NOT selected_format STREQUAL "")
  message(FATAL_ERROR "The owned preflight copy did not clear the explicit format")
endif()
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef nonce)

foreach(profile_case IN ITEMS clean one_invalid both_invalid zero maximum)
  set(case_root "${P1_ROOT_BASE}/${profile_case}-${nonce}")
  file(MAKE_DIRECTORY "${case_root}/temp" "${case_root}/AppData/Local/DREAM3DNX" "${case_root}/AppData/Roaming" "${case_root}/Library/Preferences/DREAM3DNX" "${case_root}/.config/DREAM3DNX")
  if(WIN32)
    set(preferences_file "${case_root}/AppData/Local/DREAM3DNX/preferences.json")
  elseif(APPLE)
    set(preferences_file "${case_root}/Library/Preferences/DREAM3DNX/preferences.json")
  else()
    set(preferences_file "${case_root}/.config/DREAM3DNX/preferences.json")
  endif()
  if(profile_case STREQUAL "clean")
    set(profile "{\"plugins\":{\"P1\":{\"keep\":17}}}")
    set(expected_count 0)
  elseif(profile_case STREQUAL "one_invalid")
    set(profile "{\"large_data_size\":-1,\"large_datastructure_size\":18446744073709551615,\"plugins\":{\"P1\":{\"keep\":17}}}")
    set(expected_count 1)
  elseif(profile_case STREQUAL "both_invalid")
    set(profile "{\"large_data_size\":-1,\"large_datastructure_size\":\"bad\",\"plugins\":{\"P1\":{\"keep\":17}}}")
    set(expected_count 2)
  elseif(profile_case STREQUAL "zero")
    set(profile "{\"large_data_size\":0,\"large_datastructure_size\":0,\"plugins\":{\"P1\":{\"keep\":17}}}")
    set(expected_count 0)
  else()
    set(profile "{\"large_data_size\":18446744073709551615,\"large_datastructure_size\":18446744073709551615,\"plugins\":{\"P1\":{\"keep\":17}}}")
    set(expected_count 0)
  endif()
  file(WRITE "${preferences_file}" "${profile}")
  file(WRITE "${case_root}/input-preferences.json" "${profile}")
  file(WRITE "${case_root}/pipeline.d3dpipeline" "${pipeline}")

  set(ENV{HOME} "${case_root}")
  set(ENV{USERPROFILE} "${case_root}")
  set(ENV{LOCALAPPDATA} "${case_root}/AppData/Local")
  set(ENV{APPDATA} "${case_root}/AppData/Roaming")
  set(ENV{TEMP} "${case_root}/temp")
  set(ENV{TMP} "${case_root}/temp")
  set(ENV{TMPDIR} "${case_root}/temp")
  unset(ENV{SIMPLNX_OOC_FAULT_INJECT})
  execute_process(COMMAND "${NXRUNNER_EXECUTABLE}" --preflight "${case_root}/pipeline.d3dpipeline"
    WORKING_DIRECTORY "${case_root}" RESULT_VARIABLE run_status OUTPUT_FILE "${case_root}/stdout.txt"
    ERROR_FILE "${case_root}/stderr.txt" TIMEOUT 120)
  simplnx_classify_ooc_process_status("${run_status}" classification)
  if(NOT classification STREQUAL "SUCCESS")
    message(FATAL_ERROR "${profile_case} preflight failed with '${run_status}'; evidence: ${case_root}")
  endif()
  file(READ "${case_root}/stdout.txt" stdout)
  file(READ "${case_root}/stderr.txt" stderr)
  string(REGEX MATCHALL "Warning -591: [^\r\n]+" corrections "${stderr}")
  list(LENGTH corrections correction_count)
  if(NOT correction_count EQUAL expected_count)
    message(FATAL_ERROR "${profile_case}: expected ${expected_count} corrections, got ${correction_count}; evidence: ${case_root}")
  endif()
  if(stdout MATCHES "Warning -591:")
    message(FATAL_ERROR "${profile_case}: correction appeared on stdout; evidence: ${case_root}")
  endif()
  set(array_corrections 0)
  set(structure_corrections 0)
  foreach(correction IN LISTS corrections)
    string(STRIP "${correction}" correction)
    if(correction MATCHES "large_data_size")
      math(EXPR array_corrections "${array_corrections}+1")
      if(NOT correction STREQUAL expected_array_line)
        message(FATAL_ERROR "${profile_case}: array correction differs from the exact core message; evidence: ${case_root}\n${correction}")
      endif()
    elseif(correction MATCHES "large_datastructure_size")
      math(EXPR structure_corrections "${structure_corrections}+1")
      if(NOT correction STREQUAL expected_structure_line)
        message(FATAL_ERROR "${profile_case}: structure correction differs from the exact core message; evidence: ${case_root}\n${correction}")
      endif()
    else()
      message(FATAL_ERROR "${profile_case}: unexpected correction key; evidence: ${case_root}")
    endif()
  endforeach()
  if(profile_case STREQUAL "one_invalid" AND NOT array_corrections EQUAL 1)
    message(FATAL_ERROR "${profile_case}: expected one array correction; evidence: ${case_root}")
  endif()
  if(profile_case STREQUAL "both_invalid" AND (NOT array_corrections EQUAL 1 OR NOT structure_corrections EQUAL 1))
    message(FATAL_ERROR "${profile_case}: expected one correction for each field; evidence: ${case_root}")
  endif()
  if(profile_case STREQUAL "both_invalid")
    list(GET corrections 0 first_correction)
    list(GET corrections 1 second_correction)
    if(NOT first_correction MATCHES "large_data_size" OR NOT second_correction MATCHES "large_datastructure_size")
      message(FATAL_ERROR "${profile_case}: correction order changed; evidence: ${case_root}")
    endif()
  endif()
  file(READ "${preferences_file}" saved)
  string(JSON kept GET "${saved}" plugins P1 keep)
  if(NOT kept STREQUAL "17")
    message(FATAL_ERROR "${profile_case}: unrelated plugin value changed; evidence: ${case_root}")
  endif()
  if(profile_case STREQUAL "one_invalid" OR profile_case STREQUAL "maximum")
    if(NOT saved MATCHES "\"large_datastructure_size\"[ \t]*:[ \t]*18446744073709551615[ \t]*[,}]")
      message(FATAL_ERROR "${profile_case}: UINT64_MAX was narrowed; evidence: ${case_root}")
    endif()
  endif()
  if(profile_case STREQUAL "maximum" AND NOT saved MATCHES "\"large_data_size\"[ \t]*:[ \t]*18446744073709551615[ \t]*[,}]")
    message(FATAL_ERROR "${profile_case}: per-array UINT64_MAX was narrowed; evidence: ${case_root}")
  endif()
  if(profile_case STREQUAL "zero" AND (NOT saved MATCHES "\"large_data_size\"[ \t]*:[ \t]*0[ \t]*[,}]" OR NOT saved MATCHES "\"large_datastructure_size\"[ \t]*:[ \t]*0[ \t]*[,}]"))
    message(FATAL_ERROR "${profile_case}: zero threshold did not survive normal saving; evidence: ${case_root}")
  endif()
endforeach()
