name: Performance Report
description: File a performance report
title: "PERF: "
labels: ["performance", "needs triage"]
body:
  - type: markdown
    attributes:
      value: |
        We're sorry to hear your having trouble with our library. By filling out the following form in its entirety, we will be able to better diagnose the problem and help you reach a resolution. Thank you in advance for taking the time to fill out the form!
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the performance issue you encountered.
      options:
        - label: I have searched the existing issues, known issues in release notes, and documentation.
          required: true
  - type: textarea
    id: brief-description
    attributes:
      label: Brief Description of the Issue and Expected Behavior
      description: Briefly describe the issue you encountered and what you expected to happen.
      placeholder: Tell us what you see profiling wise.
      value: "This profile shows..."
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running? [Further details may be required during triage process]
      options:
        - DREAM3D NX (version 7)
        - NXRunner built from source - Please provide git hash of commit in description
        - other (Please enter in the extended description at the bottom)
    validations:
      required: true
  - type: dropdown
    id: operating-system
    attributes:
      label: What operating system are you seeing the problem on? [Further details may be required during triage process]
      options:
        - Windows 10
        - Windows 11
        - macOS 11.00 Big Sur
        - macOS 12.00 Monterey
        - macOS 13.00 Ventura
        - Linux - Ubuntu 20.04 LTS
        - Linux - Ubuntu 22.04 LTS
        - other (Please enter in the extended description at the bottom)
    validations:
      required: true
  - type: dropdown
    id: hardware-architecture
    attributes:
      label: What hardware architecture are you using? [Further details may be required during triage process]
      options:
        - x86_64
        - x64
        - ARM64
        - other (Please enter in the extended description at the bottom)
    validations:
      required: true
  - type: dropdown
    id: error-type
    attributes:
      label: What section did you encounter the deprecated performance in? [Further details may be required during triage process]
      multiple: true
      options:
        - GUI client
        - NXRunner
        - Python Bindings
        - Specific filter
    validations:
      required: false
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps To Reproduce
      description: Please include the steps to reproduce the behavior in order to help you as efficiently as possible.
      placeholder: |
        1. With this config...
        2. Run '...'
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This can be found in the output widget of the interface or the console output of PipelineRunner.
      render: "Text"
    validations:
      required: false
  - type: textarea
    id: further-detail
    attributes:
      label: Anything else?
      description: |
        Pipeline? Data? References? Compiler? Hardware? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you understand that your issue may be closed if you do not remain cordial, do not provide further detail if prompted, or do not engage with responses from the developers in a reasonable time.
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
