{% set name = "simplnx" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - path: ../
    folder: simplnx
  - git_url: https://github.com/BlueQuartzSoftware/EbsdLib
    git_rev: v1.0.30
    folder: EbsdLib
  - git_url: https://github.com/BlueQuartzSoftware/H5Support
    git_rev: v1.0.13
    folder: H5Support
  - git_url: https://github.com/martinmoene/expected-lite
    git_rev: v0.8.0
    folder: expected-lite
  - git_url: https://github.com/fr00b0/nod
    git_rev: v0.5.4
    folder: nod
  - git_url: https://github.com/martinmoene/span-lite
    git_rev: v0.11.0
    folder: span-lite
  - url: https://raw.githubusercontent.com/BlueQuartzSoftware/simplnx-registry/9a5db7b5fa02b2495eb51654cbaab3c63820c779/ports/nod/CMakeLists.txt
    folder: nod
  - git_url: https://github.com/insightsoftwareconsortium/ITK
    git_rev: v5.2.1
    folder: itk

build:
  number: 0
  script_env:
    - SIMPLNX_CMAKE_PRESET=conda-win # [win]
    - SIMPLNX_CMAKE_PRESET=conda-linux # [linux]
    - SIMPLNX_CMAKE_PRESET=conda-osx # [osx]
    - ITK_VERSION=5.2.1

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake =3.26
    - ninja
    - git
  host:
    - python {{ python }}
    - numpy >=1.16
    - mypy
    - boost_mp11
    - eigen
    - fmt =10
    - hdf5 >=1.14.3 # [py>=312]
    - hdf5 =1.12 # [py<=311]
    - nlohmann_json
    - pybind11 >=2.10
    - reproc-cpp
    - tbb
    - tbb-devel
    - zlib
    - sphinx
    - myst-parser
    - sphinx-markdown-tables
    - sphinx_rtd_theme

  run:
    - python
    - numpy
    - fmt =10
    - hdf5 >=1.14.3 # [py>=312]
    - hdf5 =1.12 # [py<=311]
    - reproc-cpp
    - tbb
    - zlib

test:
  imports:
    - simplnx

about:
  home: https://www.dream3d.io/
  license: BSD
  summary: DREAM3D-NX consists of data analysis tools (Filters) that allow for the construction of customized workflows (Pipelines) to analyze data.
