context:
  version: "1.2.6"
  name: simplnx

package:
  name: "{{ name }}"
  version: "{{ version }}"

source:
  - path: ../
    folder: simplnx
  - git_url: https://github.com/BlueQuartzSoftware/EbsdLib
    git_rev: v1.0.26
    folder: EbsdLib
  - git_url: https://github.com/BlueQuartzSoftware/H5Support
    git_rev: v1.0.13
    folder: H5Support
  - git_url: https://github.com/martinmoene/expected-lite
    git_rev: v0.5.0
    folder: expected-lite
  - git_url: https://github.com/fr00b0/nod
    git_rev: v0.5.2
    folder: nod
  - git_url: https://github.com/martinmoene/span-lite
    git_rev: v0.10.3
    folder: span-lite
  - url: https://raw.githubusercontent.com/bluequartzsoftware/simplnx-registry/9a5db7b5fa02b2495eb51654cbaab3c63820c779/ports/nod/CMakeLists.txt
    folder: nod
  - git_url: https://github.com/insightsoftwareconsortium/ITK
    git_rev: v5.2.1
    folder: itk
    
build:
  number: 0
  script_env:
    sel(linux):
      SIMPLNX_CMAKE_PRESET: "conda-linux"
    sel(osx):
      SIMPLNX_CMAKE_PRESET: "conda-osx"

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - cmake >=3.26
    - ninja
    - git
  host:
    - python
    - mypy
    - numpy >=1.16
    - boost_mp11
    - eigen
    - fmt =10
    - sel(py>=312):
      - hdf5 >=1.14.3
    - sel(py>=39 and py<312):
      - hdf5 >=1.12
    - nlohmann_json
    - pybind11 >=2.10
    - reproc-cpp
    - tbb
    - tbb-devel
    - zlib
    - sphinx
    - myst-parser
    - sphinx-markdown-tables
    - sphinx_rtd_theme
  run:
    - python
    - numpy
    - fmt =10
    - sel(py>=312):
      - hdf5 >=1.14.3
    - sel(py>=39 and py<312):
      - hdf5 >=1.12
    - reproc-cpp
    - tbb
    - zlib

test:
  imports:
    - simplnx

about:
  home: http://dream3d.bluequartz.net/
  license: BSD
  summary: DREAM.3D consists of data analysis tools (Filters) that allow for the construction of customized workflows (Pipelines) to analyze data.
