name: macos

on:
  pull_request:
    branches:
      - develop
      - master
  push:
    branches:
      - develop
      - master

jobs:
  build:
    env:
      VCPKG_BINARY_SOURCES: 'clear;nuget,GitHub,readwrite'
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-12
          - macos-14
        include:
          - os: macos-12
            preset: ci-macos-x64
          - os: macos-14
            preset: ci-macos-arm64
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Checkout vcpkg
        run: |
            git clone https://www.github.com/microsoft/vcpkg && cd vcpkg && ./bootstrap-vcpkg.sh
            VCPKG_INSTALLATION_ROOT=${{github.workspace}}/vcpkg
            echo "$VCPKG_INSTALLATION_ROOT" >> $GITHUB_PATH
            echo "VCPKG_INSTALLATION_ROOT=$VCPKG_INSTALLATION_ROOT" >> "$GITHUB_ENV"
        if: matrix.os == 'macos-14'
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx myst-parser sphinx-markdown-tables sphinx_rtd_theme numpy
      - name: Add C++ Problem Matcher
        uses: ammaraskar/gcc-problem-matcher@0.2.0
      - name: Install Dependencies - 2
        run: |
          brew install ninja
      - name: Install Sphinx
        run: |
          sudo pip3 install sphinx myst-parser sphinx-markdown-tables sphinx_rtd_theme numpy
      - name: Setup NuGet Credentials
        shell: bash
        run: |
          mono `vcpkg fetch nuget | tail -n 1` \
          sources add \
          -source "https://nuget.pkg.github.com/BlueQuartzSoftware/index.json" \
          -storepasswordincleartext \
          -name "GitHub" \
          -username "BlueQuartzSoftware" \
          -password "${{secrets.GITHUB_TOKEN}}"
          mono `vcpkg fetch nuget | tail -n 1` \
          setapikey "${{secrets.GITHUB_TOKEN}}" \
          -source "https://nuget.pkg.github.com/BlueQuartzSoftware/index.json"
      - name: Configure
        run: |
          cmake --preset ${{matrix.preset}} ${{github.workspace}}
      - name: Build
        run: |
          cmake --build --preset ${{matrix.preset}}
      - name: Test
        run: |
          ctest --preset ${{matrix.preset}}
