name: asan

on:
  schedule:
    - cron: '15 5 * * *'

jobs:
  build:
    env:
      VCPKG_BINARY_SOURCES: 'clear;nuget,GitHub,readwrite'
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Add C++ Problem Matcher
        uses: ammaraskar/gcc-problem-matcher@0.2.0
      - name: Install Dependencies
        run: |
          sudo apt-get -y install ninja-build
      - name: Setup NuGet Credentials
        shell: bash
        run: |
          mono `vcpkg fetch nuget | tail -n 1` \
          sources add \
          -source "https://nuget.pkg.github.com/BlueQuartzSoftware/index.json" \
          -storepasswordincleartext \
          -name "GitHub" \
          -username "BlueQuartzSoftware" \
          -password "${{secrets.GITHUB_TOKEN}}"
          mono `vcpkg fetch nuget | tail -n 1` \
          setapikey "${{secrets.GITHUB_TOKEN}}" \
          -source "https://nuget.pkg.github.com/BlueQuartzSoftware/index.json"
      - name: Configure
        env:
          CC: clang-10
          CXX: clang++-10
        run: |
          cmake --preset ci-asan ${{github.workspace}}
      - name: Build
        run: |
          cmake --build --preset ci-asan
      - name: Test
        run: |
          ctest --preset ci-asan
