name: asan

on:
  schedule:
    - cron: '15 5 * * *'

jobs:
  build:
    env:
      VCPKG_BINARY_SOURCES: 'clear;nuget,GitHub,readwrite'
      CC: clang-17
      CXX: clang++-17
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: true
      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.10'
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx myst-parser sphinx-markdown-tables sphinx_rtd_theme numpy
      - name: Add C++ Problem Matcher
        uses: ammaraskar/gcc-problem-matcher@cb2e3f949c41b7818628f35f8484a9b0acf90cf9
      - name: Install mono
        shell: bash
        run: |
          sudo apt-get -y install ca-certificates gnupg
          sudo gpg --homedir /tmp --no-default-keyring --keyring /usr/share/keyrings/mono-official-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
          echo "deb [signed-by=/usr/share/keyrings/mono-official-archive-keyring.gpg] https://download.mono-project.com/repo/ubuntu stable-focal main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
          sudo apt-get -y update
          sudo apt-get -y install mono-complete
      - name: Setup NuGet Credentials
        shell: bash
        run: |
          mono `vcpkg fetch nuget | tail -n 1` \
          sources add \
          -source "https://nuget.pkg.github.com/BlueQuartzSoftware/index.json" \
          -storepasswordincleartext \
          -name "GitHub" \
          -username "BlueQuartzSoftware" \
          -password "${{secrets.GITHUB_TOKEN}}"
          mono `vcpkg fetch nuget | tail -n 1` \
          setapikey "${{secrets.GITHUB_TOKEN}}" \
          -source "https://nuget.pkg.github.com/BlueQuartzSoftware/index.json"
      - name: Configure
        run: |
          cmake --preset ci-asan ${{github.workspace}}
      - name: Build
        run: |
          export LD_LIBRARY_PATH=$(dirname $($CXX -print-file-name=libclang_rt.asan-x86_64.so))
          cmake --build --preset ci-asan
      - name: Test
        run: |
          export LD_PRELOAD=$($CXX -print-file-name=libclang_rt.asan-x86_64.so)
          export LSAN_OPTIONS=suppressions=${{github.workspace}}/utilities/leak_suppressions.txt
          ctest --preset ci-asan
