name: clang-format

on:
  push:
    branches:
      - develop
      - master

jobs:
  clang_format:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v7
      - name: Add Problem Matcher
        uses: ammaraskar/gcc-problem-matcher@cb2e3f949c41b7818628f35f8484a9b0acf90cf9
      - name: Install clang-format-19
        run: |
          sudo apt-get update
          sudo apt-get install clang-format-19
          clang-format-19 --version
      - name: Check Formatting
        run: |
          python3 scripts/clang_format.py --format-version 19
