name: windows

on:
  pull_request:
    branches:
      - develop
      - master
  push:
    branches:
      - develop
      - master

jobs:
  build:
    env:
      VCPKG_BINARY_SOURCES: 'clear;nuget,GitHub,readwrite'
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-2022
        toolset:
          - v142
          - v143
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Checkout DREAM3D_Data Repo
        uses: actions/checkout@v2
        with:
          repository: DREAM3D/DREAM3D_Data
          path: DREAM3D_Data
          submodules: true
      - name: Add C++ Problem Matcher
        uses: ammaraskar/msvc-problem-matcher@0.2.0
      - name: Setup Build Environment
        uses: ilammy/msvc-dev-cmd@v1.12.0
        with:
          vsversion: 2022
      - name: Setup NuGet Credentials
        shell: bash
        run: |
          `vcpkg fetch nuget | tail -n 1` \
          sources add \
          -source "https://nuget.pkg.github.com/BlueQuartzSoftware/index.json" \
          -storepasswordincleartext \
          -name "GitHub" \
          -username "BlueQuartzSoftware" \
          -password "${{secrets.GITHUB_TOKEN}}"
          `vcpkg fetch nuget | tail -n 1` \
          setapikey "${{secrets.GITHUB_TOKEN}}" \
          -source "https://nuget.pkg.github.com/BlueQuartzSoftware/index.json"
      - name: Configure
        run: |
          cmake --preset ci ${{github.workspace}} -G "Visual Studio 17 2022" -T ${{matrix.toolset}}  -D DREAM3D_DATA_DIR=${{github.workspace}}/DREAM3D_Data -DVCPKG_MANIFEST_FEATURES="tests;parallel;itk;ebsd" -DCOMPLEX_EXTRA_PLUGINS="ITKImageProcessing;OrientationAnalysis"
      - name: Build
        run: |
          cmake --build --preset ci
      - name: Test
        run: |
          ctest --preset ci
