name: windows

on:
  pull_request:
    branches:
      - develop
      - master
  push:
    branches:
      - develop
      - master

jobs:
  build:
    env:
      VCPKG_BINARY_SOURCES: 'clear;nuget,GitHub,readwrite'
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-2022
        toolset:
          - v142
          - v143
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Checkout Complex Repo
        uses: actions/checkout@v2
        with:
          repository: bluequartzsoftware/complex
          path: complex
          submodules: true
      - name: Checkout DREAM3D_Data Repo
        uses: actions/checkout@v2
        with:
          repository: DREAM3D/DREAM3D_Data
          path: DREAM3D_Data
          submodules: true
      - name: Add C++ Problem Matcher
        uses: ammaraskar/msvc-problem-matcher@0.2.0
      - name: Setup Build Environment
        uses: ilammy/msvc-dev-cmd@v1.12.0
        with:
          vsversion: 2022

      - name: Setup NuGet Credentials
        shell: bash
        run: >
          `vcpkg fetch nuget | tail -n 1`
          sources add
          -source "https://nuget.pkg.github.com/BlueQuartzSoftware/index.json"
          -storepasswordincleartext
          -name "GitHub"
          -username "BlueQuartzSoftware"
          -password "${{secrets.GITHUB_TOKEN}}"
      - name: Configure
        run: |
          cd ${{github.workspace}}/complex && cmake --preset ci  -G "Visual Studio 17 2022" -T ${{matrix.toolset}} -DDREAM3D_DATA_DIR=${{github.workspace}}/DREAM3D_Data -DCOMPLEX_EXTRA_PLUGINS="Core;OrientationAnalysis" -DCOMPLEX_PLUGIN_SEARCH_DIRS=${{github.workspace}} -S ${{github.workspace}}/complex 
      - name: Build
        run: |
          cd ${{github.workspace}}/complex && cmake --build --preset ci
      - name: Test
        run: |
          cd ${{github.workspace}}/complex && ctest --preset ci
