#include "SimplnxCore/Filters/ComputeEuclideanDistMapFilter.hpp"
#include "SimplnxCore/SimplnxCore_test_dirs.hpp"

#include "simplnx/Core/Application.hpp"
#include "simplnx/DataStructure/Geometry/ImageGeom.hpp"
#include "simplnx/Parameters/ArrayCreationParameter.hpp"
#include "simplnx/Parameters/BoolParameter.hpp"
#include "simplnx/Pipeline/Pipeline.hpp"
#include "simplnx/Pipeline/PipelineFilter.hpp"
#include "simplnx/UnitTest/UnitTestCommon.hpp"

#include <catch2/catch.hpp>

#include <algorithm>
#include <array>
#include <cmath>
#include <filesystem>
#include <fstream>
#include <limits>
#include <string>
#include <vector>

using namespace nx::core;
using namespace nx::core::Constants;
using namespace nx::core::UnitTest;
namespace fs = std::filesystem;

namespace
{
const std::string k_CalculatedPrefix = "Calculated_";
const std::string k_GBDistancesArrayName = "GBManhattanDistances";
const std::string k_TJDistancesArrayName = "TJManhattanDistances";
const std::string k_QPDistancesArrayName = "QPManhattanDistances";

bool ArrayExists(const DataStructure& dataStructure, const std::string& name)
{
  const DataPath calculatedPath({k_DataContainer, k_CellData, std::string(k_CalculatedPrefix) + name});
  return dataStructure.getDataAs<IDataArray>(calculatedPath) != nullptr;
};

// ============================================================================================
// V&V fixture harness (Class 1 analytical + Class 4 invariant)
//
// SEMANTICS WARNING -- finding ED-1. The float32 output of this filter is NOT a Euclidean
// distance transform. It is the straight-line distance from each cell to *the one particular
// seed cell that the breadth-first propagation happened to hand it*, and that seed is chosen by
// a tie-break, not by proximity. The propagation loop
// (Algorithms/ComputeEuclideanDistMap.cpp:185-200) assigns
//     voxel_NearestNeighbor[i] = voxel_NearestNeighbor[neighpoint]
// UNCONDITIONALLY inside a j = 0..5 loop over the offsets
//     { -nx*ny, -nx, -1, +1, +nx, +nx*ny }  ==  { -z, -y, -x, +x, +y, +z },
// so the LAST qualifying neighbour wins and the descending priority is
//
//     +z  >  +y  >  +x  >  -x  >  -y  >  -z
//
// The consequence is asserted below and is load-bearing: in fixture A, cell 0 gets
// gbEuclidean == 4.0 even though a boundary seed exists 2.0 away. See the ED-1 comment on
// fixture A in the generated table.
// ============================================================================================

const std::string k_TestImageGeomName = "TestImageGeometry";
const std::string k_TestCellDataName = "TestCellData";
const std::string k_TestFeatureIdsName = "TestFeatureIds";
const DataPath k_TestImageGeomPath({k_TestImageGeomName});
const DataPath k_TestCellDataPath = k_TestImageGeomPath.createChildPath(k_TestCellDataName);
const DataPath k_TestFeatureIdsPath = k_TestCellDataPath.createChildPath(k_TestFeatureIdsName);
const DataPath k_TestGBPath = k_TestCellDataPath.createChildPath(k_GBDistancesArrayName);
const DataPath k_TestTJPath = k_TestCellDataPath.createChildPath(k_TJDistancesArrayName);
const DataPath k_TestQPPath = k_TestCellDataPath.createChildPath(k_QPDistancesArrayName);

struct Fixture
{
  std::string tag;
  SizeVec3 dims;
  FloatVec3 spacing;
  std::vector<int32> featureIds;
  std::vector<int32> gbManhattan;
  std::vector<int32> tjManhattan;
  std::vector<int32> qpManhattan;
  std::vector<float32> gbEuclidean;
  std::vector<float32> tjEuclidean;
  std::vector<float32> qpEuclidean;
  std::string note;
};
// clang-format off
// ============================================================================
// Expected values. GENERATED by ww_work/ComputeEuclideanDistMap/gen_expected.py from
// oracle.py, an independent re-implementation of the seed rule, the layer-synchronous
// propagation, the +z>+y>+x>-x>-y>-z tie-break and the reciprocal coordinate decode --
// all read off Algorithms/ComputeEuclideanDistMap.cpp and written BEFORE the filter was
// ever run on these fixtures. Do not hand-edit: regenerate.
// ============================================================================
const std::vector<Fixture> k_Fixtures = {
    // ---- A: legacy 6.5.171 fixture; anisotropic sy=2; id-0 column x=8; bad-data column x=9; ED-1 tie-break pin GBEuclidean[0]=4.0 vs trueEDT 2.0
    // ED-1 (GB): the BFS tie-break hands out a FARTHER seed than the nearest one at cell 0: output 4 vs nearest-seed 2, cell 11: output 2 vs nearest-seed 1, cell 17: output 2 vs nearest-seed 1.
    {
        "A",
        SizeVec3{10, 6, 1},
        FloatVec3{1.0F, 2.0F, 1.0F},
        {1, 1, 1, 3, 3, 3, 4, 4, 4, 0, 1, 1, 1, 3, 3, 3, 4, 4, 4, 0, 1, 1, 1, 3, 3, 3, 4, 4, 4, 0, 2, 2, 2, 3, 3, 3, 5, 5, 5, 0, 2, 2, 2, 3, 3, 3, 5, 5, 5, 0, 2, 2, 2, 3, 3, 3, 5, 5, 5, 0},
        {2, 1, 0, 0, 1, 0, 0, 1, 0, -1, 1, 1, 0, 0, 1, 0, 0, 1, 0, -1, 0, 0, 0, 0, 1, 0, 0, 0, 0, -1, 0, 0, 0, 0, 1, 0, 0, 0, 0, -1, 1, 1, 0, 0, 1, 0, 0, 1, 0, -1, 2, 1, 0, 0, 1, 0, 0, 1, 0, -1}, // gbManhattan
        {4, 3, 2, 3, 4, 3, 2, 3, 2, -1, 3, 2, 1, 2, 3, 2, 1, 2, 1, -1, 2, 1, 0, 1, 2, 1, 0, 1, 0, -1, 2, 1, 0, 1, 2, 1, 0, 1, 0, -1, 3, 2, 1, 2, 3, 2, 1, 2, 1, -1, 4, 3, 2, 3, 4, 3, 2, 3, 2, -1}, // tjManhattan
        {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, // qpManhattan
        {4.0F, 1.0F, 0.0F, 0.0F, 1.0F, 0.0F, 0.0F, 1.0F, 0.0F, -1.0F, 2.0F, 2.0F, 0.0F, 0.0F, 1.0F, 0.0F, 0.0F, 2.0F, 0.0F, -1.0F, 0.0F, 0.0F, 0.0F, 0.0F, 1.0F, 0.0F, 0.0F, 0.0F, 0.0F, -1.0F, 0.0F, 0.0F, 0.0F, 0.0F, 1.0F, 0.0F, 0.0F, 0.0F, 0.0F, -1.0F, 2.0F, 1.0F, 0.0F, 0.0F, 1.0F, 0.0F, 0.0F, 1.0F, 0.0F, -1.0F, 2.0F, 1.0F, 0.0F, 0.0F, 1.0F, 0.0F, 0.0F, 1.0F, 0.0F, -1.0F}, // gbEuclidean
        {4.4721359549995796F, 4.1231056256176606F, 4.0F, 4.1231056256176606F, 4.4721359549995796F, 4.1231056256176606F, 4.0F, 4.1231056256176606F, 4.0F, -1.0F, 2.8284271247461903F, 2.2360679774997898F, 2.0F, 2.2360679774997898F, 2.8284271247461903F, 2.2360679774997898F, 2.0F, 2.2360679774997898F, 2.0F, -1.0F, 2.0F, 1.0F, 0.0F, 1.0F, 2.0F, 1.0F, 0.0F, 1.0F, 0.0F, -1.0F, 2.0F, 1.0F, 0.0F, 1.0F, 2.0F, 1.0F, 0.0F, 1.0F, 0.0F, -1.0F, 2.8284271247461903F, 2.2360679774997898F, 2.0F, 2.2360679774997898F, 2.8284271247461903F, 2.2360679774997898F, 2.0F, 2.2360679774997898F, 2.0F, -1.0F, 4.4721359549995796F, 4.1231056256176606F, 4.0F, 4.1231056256176606F, 4.4721359549995796F, 4.1231056256176606F, 4.0F, 4.1231056256176606F, 4.0F, -1.0F}, // tjEuclidean
        {-1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F}, // qpEuclidean
        "legacy 6.5.171 fixture; anisotropic sy=2; id-0 column x=8; bad-data column x=9; ED-1 tie-break pin GBEuclidean[0]=4.0 vs trueEDT 2.0",
    },
    // ---- B: 1D two-feature split; GB == {2,1,0,0,1,2} in both modes
    {
        "B",
        SizeVec3{6, 1, 1},
        FloatVec3{1.0F, 1.0F, 1.0F},
        {1, 1, 1, 2, 2, 2},
        {2, 1, 0, 0, 1, 2}, // gbManhattan
        {-1, -1, -1, -1, -1, -1}, // tjManhattan
        {-1, -1, -1, -1, -1, -1}, // qpManhattan
        {2.0F, 1.0F, 0.0F, 0.0F, 1.0F, 2.0F}, // gbEuclidean
        {-1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F}, // tjEuclidean
        {-1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F}, // qpEuclidean
        "1D two-feature split; GB == {2,1,0,0,1,2} in both modes",
    },
    // ---- C: 2D triple junction; two TJ seeds; sqrt(2) in the TJ euclidean map
    {
        "C",
        SizeVec3{3, 3, 1},
        FloatVec3{1.0F, 1.0F, 1.0F},
        {3, 3, 3, 1, 2, 2, 1, 2, 2},
        {0, 0, 0, 0, 0, 0, 0, 0, 1}, // gbManhattan
        {1, 1, 2, 0, 0, 1, 1, 1, 2}, // tjManhattan
        {-1, -1, -1, -1, -1, -1, -1, -1, -1}, // qpManhattan
        {0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 1.0F}, // gbEuclidean
        {1.0F, 1.0F, 1.4142135623730951F, 0.0F, 0.0F, 1.0F, 1.0F, 1.0F, 1.4142135623730951F}, // tjEuclidean
        {-1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F}, // qpEuclidean
        "2D triple junction; two TJ seeds; sqrt(2) in the TJ euclidean map",
    },
    // ---- D: 2D pinwheel QUAD POINT -- quad points do not require 3D
    {
        "D",
        SizeVec3{3, 3, 1},
        FloatVec3{1.0F, 1.0F, 1.0F},
        {4, 5, 5, 4, 1, 3, 2, 2, 3},
        {0, 0, 0, 0, 0, 0, 0, 0, 0}, // gbManhattan
        {1, 0, 1, 0, 0, 0, 1, 0, 1}, // tjManhattan
        {2, 1, 2, 1, 0, 1, 2, 1, 2}, // qpManhattan
        {0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F}, // gbEuclidean
        {1.0F, 0.0F, 1.0F, 0.0F, 0.0F, 0.0F, 1.0F, 0.0F, 1.0F}, // tjEuclidean
        {1.4142135623730951F, 1.0F, 1.4142135623730951F, 1.0F, 0.0F, 1.0F, 1.4142135623730951F, 1.0F, 1.4142135623730951F}, // qpEuclidean
        "2D pinwheel QUAD POINT -- quad points do not require 3D",
    },
    // ---- Dz: 3D z-layered; isolates R4's z-decode against spacing[2]=4
    {
        "Dz",
        SizeVec3{3, 3, 3},
        FloatVec3{1.0F, 1.0F, 4.0F},
        {1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2},
        {1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, // gbManhattan
        {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, // tjManhattan
        {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, // qpManhattan
        {4.0F, 4.0F, 4.0F, 4.0F, 4.0F, 4.0F, 4.0F, 4.0F, 4.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F}, // gbEuclidean
        {-1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F}, // tjEuclidean
        {-1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F}, // qpEuclidean
        "3D z-layered; isolates R4's z-decode against spacing[2]=4",
    },
    // ---- E: single feature: no seeds in any tier, everything stays -1
    {
        "E",
        SizeVec3{3, 3, 1},
        FloatVec3{1.0F, 1.0F, 1.0F},
        {1, 1, 1, 1, 1, 1, 1, 1, 1},
        {-1, -1, -1, -1, -1, -1, -1, -1, -1}, // gbManhattan
        {-1, -1, -1, -1, -1, -1, -1, -1, -1}, // tjManhattan
        {-1, -1, -1, -1, -1, -1, -1, -1, -1}, // qpManhattan
        {-1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F}, // gbEuclidean
        {-1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F}, // tjEuclidean
        {-1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F}, // qpEuclidean
        "single feature: no seeds in any tier, everything stays -1",
    },
    // ---- F: all id 0: everything -1 in SIMPLNX. ED-2 pin (legacy float writes 0.0)
    {
        "F",
        SizeVec3{3, 3, 1},
        FloatVec3{1.0F, 1.0F, 1.0F},
        {0, 0, 0, 0, 0, 0, 0, 0, 0},
        {-1, -1, -1, -1, -1, -1, -1, -1, -1}, // gbManhattan
        {-1, -1, -1, -1, -1, -1, -1, -1, -1}, // tjManhattan
        {-1, -1, -1, -1, -1, -1, -1, -1, -1}, // qpManhattan
        {-1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F}, // gbEuclidean
        {-1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F}, // tjEuclidean
        {-1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F, -1.0F}, // qpEuclidean
        "all id 0: everything -1 in SIMPLNX. ED-2 pin (legacy float writes 0.0)",
    },
};
// clang-format on

// The four toggle sets each fixture is run under. The all-three entry is also the
// ParallelTaskAlgorithm determinism probe (see the Parallel Determinism TEST_CASE).
struct ToggleSet
{
  const char* label;
  bool doBoundaries;
  bool doTripleLines;
  bool doQuadPoints;
};
const std::vector<ToggleSet> k_ToggleSets = {
    {"GB only", true, false, false},
    {"TJ only", false, true, false},
    {"QP only", false, false, true},
    {"all three", true, true, true},
};

DataStructure BuildFixture(const Fixture& fixture)
{
  DataStructure dataStructure;
  auto* imageGeom = ImageGeom::Create(dataStructure, k_TestImageGeomName);
  imageGeom->setDimensions(fixture.dims);
  imageGeom->setSpacing(fixture.spacing);
  imageGeom->setOrigin(FloatVec3{0.0F, 0.0F, 0.0F});

  // AttributeMatrix / DataArray tuple shapes run slowest-to-fastest (Z, Y, X); ImageGeom
  // dimensions run X, Y, Z.
  const ShapeType tupleShape{fixture.dims[2], fixture.dims[1], fixture.dims[0]};
  auto* cellData = AttributeMatrix::Create(dataStructure, k_TestCellDataName, tupleShape, imageGeom->getId());

  auto featureIdsStorePtr = std::make_shared<Int32DataStore>(tupleShape, ShapeType{1}, 0);
  auto* featureIdsArray = Int32Array::Create(dataStructure, k_TestFeatureIdsName, featureIdsStorePtr, cellData->getId());
  auto& featureIdsRef = featureIdsArray->getDataStoreRef();
  REQUIRE(featureIdsRef.getNumberOfTuples() == fixture.featureIds.size());
  for(usize i = 0; i < fixture.featureIds.size(); i++)
  {
    featureIdsRef[i] = fixture.featureIds[i];
  }
  return dataStructure;
}

Arguments MakeArgs(bool calcManhattan, const ToggleSet& toggles)
{
  Arguments args;
  args.insertOrAssign(ComputeEuclideanDistMapFilter::k_CalcManhattanDist_Key, std::make_any<bool>(calcManhattan));
  args.insertOrAssign(ComputeEuclideanDistMapFilter::k_DoBoundaries_Key, std::make_any<bool>(toggles.doBoundaries));
  args.insertOrAssign(ComputeEuclideanDistMapFilter::k_DoTripleLines_Key, std::make_any<bool>(toggles.doTripleLines));
  args.insertOrAssign(ComputeEuclideanDistMapFilter::k_DoQuadPoints_Key, std::make_any<bool>(toggles.doQuadPoints));
  args.insertOrAssign(ComputeEuclideanDistMapFilter::k_SelectedImageGeometryPath_Key, std::make_any<DataPath>(k_TestImageGeomPath));
  args.insertOrAssign(ComputeEuclideanDistMapFilter::k_CellFeatureIdsArrayPath_Key, std::make_any<DataPath>(k_TestFeatureIdsPath));
  args.insertOrAssign(ComputeEuclideanDistMapFilter::k_GBDistancesArrayName_Key, std::make_any<std::string>(k_GBDistancesArrayName));
  args.insertOrAssign(ComputeEuclideanDistMapFilter::k_TJDistancesArrayName_Key, std::make_any<std::string>(k_TJDistancesArrayName));
  args.insertOrAssign(ComputeEuclideanDistMapFilter::k_QPDistancesArrayName_Key, std::make_any<std::string>(k_QPDistancesArrayName));
  return args;
}

void RunFilter(DataStructure& dataStructure, bool calcManhattan, const ToggleSet& toggles)
{
  ComputeEuclideanDistMapFilter filter;
  const Arguments args = MakeArgs(calcManhattan, toggles);
  auto preflightResult = filter.preflight(dataStructure, args);
  SIMPLNX_RESULT_REQUIRE_VALID(preflightResult.outputActions)
  auto executeResult = filter.execute(dataStructure, args);
  SIMPLNX_RESULT_REQUIRE_VALID(executeResult.result)
}

std::vector<int32> ReadInt32(const DataStructure& dataStructure, const DataPath& path)
{
  REQUIRE_NOTHROW(dataStructure.getDataRefAs<Int32Array>(path));
  const auto& arrayRef = dataStructure.getDataRefAs<Int32Array>(path).getDataStoreRef();
  std::vector<int32> out(arrayRef.getNumberOfTuples());
  for(usize i = 0; i < out.size(); i++)
  {
    out[i] = arrayRef[i];
  }
  return out;
}

std::vector<float32> ReadFloat32(const DataStructure& dataStructure, const DataPath& path)
{
  REQUIRE_NOTHROW(dataStructure.getDataRefAs<Float32Array>(path));
  const auto& arrayRef = dataStructure.getDataRefAs<Float32Array>(path).getDataStoreRef();
  std::vector<float32> out(arrayRef.getNumberOfTuples());
  for(usize i = 0; i < out.size(); i++)
  {
    out[i] = arrayRef[i];
  }
  return out;
}

// The three maps of one tier, selected by tier index (0 = GB, 1 = TJ, 2 = QP).
const std::array<DataPath, 3> k_TierPaths = {k_TestGBPath, k_TestTJPath, k_TestQPPath};
const std::array<const char*, 3> k_TierNames = {"GB", "TJ", "QP"};

const std::vector<int32>& ExpectedManhattan(const Fixture& fixture, usize tier)
{
  return tier == 0 ? fixture.gbManhattan : (tier == 1 ? fixture.tjManhattan : fixture.qpManhattan);
}

const std::vector<float32>& ExpectedEuclidean(const Fixture& fixture, usize tier)
{
  return tier == 0 ? fixture.gbEuclidean : (tier == 1 ? fixture.tjEuclidean : fixture.qpEuclidean);
}

bool TierEnabled(const ToggleSet& toggles, usize tier)
{
  return tier == 0 ? toggles.doBoundaries : (tier == 1 ? toggles.doTripleLines : toggles.doQuadPoints);
}

// Brute-force physical distance from every cell to the NEAREST seed, where the seed set is taken
// from the filter's own Manhattan output (a cell is a seed exactly when its Manhattan distance is
// 0). This is the Class 4 floor for the euclidean map and is computed here, in the test, from
// filter output plus geometry alone -- it does not consult the oracle table.
std::vector<float64> TrueEdt(const Fixture& fixture, const std::vector<int32>& manhattan)
{
  const int64 nX = static_cast<int64>(fixture.dims[0]);
  const int64 nY = static_cast<int64>(fixture.dims[1]);
  const int64 nZ = static_cast<int64>(fixture.dims[2]);
  std::vector<std::array<int64, 3>> seeds;
  for(int64 i = 0; i < static_cast<int64>(manhattan.size()); i++)
  {
    if(manhattan[i] == 0)
    {
      seeds.push_back({i % nX, (i / nX) % nY, i / (nX * nY)});
    }
  }
  std::vector<float64> out(manhattan.size(), -1.0);
  if(seeds.empty())
  {
    return out;
  }
  for(int64 i = 0; i < static_cast<int64>(manhattan.size()); i++)
  {
    if(fixture.featureIds[static_cast<usize>(i)] <= 0)
    {
      continue;
    }
    const int64 x = i % nX;
    const int64 y = (i / nX) % nY;
    const int64 z = i / (nX * nY);
    float64 best = std::numeric_limits<float64>::max();
    for(const auto& seed : seeds)
    {
      const float64 dX = static_cast<float64>(x - seed[0]) * static_cast<float64>(fixture.spacing[0]);
      const float64 dY = static_cast<float64>(y - seed[1]) * static_cast<float64>(fixture.spacing[1]);
      const float64 dZ = static_cast<float64>(z - seed[2]) * static_cast<float64>(fixture.spacing[2]);
      best = std::min(best, std::sqrt((dX * dX) + (dY * dY) + (dZ * dZ)));
    }
    out[static_cast<usize>(i)] = best;
  }
  return out;
}
} // namespace

TEST_CASE("SimplnxCore::ComputeEuclideanDistMapFilter: Class 1 - Manhattan and BFS-Seed Distance Maps", "[SimplnxCore][ComputeEuclideanDistMapFilter]")
{
  UnitTest::LoadPlugins();

  for(const auto& fixture : k_Fixtures)
  {
    for(const auto& toggles : k_ToggleSets)
    {
      for(const bool calcManhattan : {true, false})
      {
        DYNAMIC_SECTION("fixture " << fixture.tag << " / " << toggles.label << " / " << (calcManhattan ? "manhattan int32" : "euclidean float32"))
        {
          INFO("fixture note: " << fixture.note);
          DataStructure dataStructure = BuildFixture(fixture);
          RunFilter(dataStructure, calcManhattan, toggles);

          for(usize tier = 0; tier < 3; tier++)
          {
            const bool enabled = TierEnabled(toggles, tier);
            INFO("tier " << k_TierNames[tier] << " expected " << (enabled ? "present" : "absent"));
            if(!enabled)
            {
              REQUIRE(dataStructure.getDataAs<IDataArray>(k_TierPaths[tier]) == nullptr);
              continue;
            }
            if(calcManhattan)
            {
              const std::vector<int32> actual = ReadInt32(dataStructure, k_TierPaths[tier]);
              const std::vector<int32>& expected = ExpectedManhattan(fixture, tier);
              REQUIRE(actual.size() == expected.size());
              for(usize i = 0; i < expected.size(); i++)
              {
                CAPTURE(fixture.tag, k_TierNames[tier], i, expected[i], actual[i]);
                REQUIRE(actual[i] == expected[i]);
              }
            }
            else
            {
              const std::vector<float32> actual = ReadFloat32(dataStructure, k_TierPaths[tier]);
              const std::vector<float32>& expected = ExpectedEuclidean(fixture, tier);
              REQUIRE(actual.size() == expected.size());
              for(usize i = 0; i < expected.size(); i++)
              {
                CAPTURE(fixture.tag, k_TierNames[tier], i, expected[i], actual[i]);
                // Rational expectations (including the -1 fill and the 0.0 seed marker) are exact
                // in float32; the irrational ones (sqrt 2, 5, 8, 17, 20) are compared with a
                // relative tolerance whose only cause is the float64 -> float32 narrowing at
                // Algorithms/ComputeEuclideanDistMap.cpp:254-262.
                if(expected[i] == std::floor(expected[i]))
                {
                  REQUIRE(actual[i] == expected[i]);
                }
                else
                {
                  REQUIRE(actual[i] == Approx(expected[i]).epsilon(1.0e-6));
                }
              }
            }
          }
          UnitTest::CheckArraysInheritTupleDims(dataStructure);
        }
      }
    }
  }
}

TEST_CASE("SimplnxCore::ComputeEuclideanDistMapFilter: Class 4 - Invariants", "[SimplnxCore][ComputeEuclideanDistMapFilter]")
{
  UnitTest::LoadPlugins();

  for(const auto& fixture : k_Fixtures)
  {
    DYNAMIC_SECTION("fixture " << fixture.tag)
    {
      INFO("fixture note: " << fixture.note);

      // One all-three-toggles run per mode gives every tier of both maps at once.
      DataStructure manhattanDS = BuildFixture(fixture);
      RunFilter(manhattanDS, true, k_ToggleSets.back());
      DataStructure euclideanDS = BuildFixture(fixture);
      RunFilter(euclideanDS, false, k_ToggleSets.back());

      std::array<std::vector<int32>, 3> manhattan;
      std::array<std::vector<float32>, 3> euclidean;
      for(usize tier = 0; tier < 3; tier++)
      {
        manhattan[tier] = ReadInt32(manhattanDS, k_TierPaths[tier]);
        euclidean[tier] = ReadFloat32(euclideanDS, k_TierPaths[tier]);
      }

      const usize numCells = fixture.featureIds.size();

      // I1  Zero-set nesting: {QP == 0} subset of {TJ == 0} subset of {GB == 0}. A quad point is
      //     a triple line is a boundary, by the coordination-size thresholds 3 >= 2 >= 1.
      for(usize i = 0; i < numCells; i++)
      {
        CAPTURE(fixture.tag, i, manhattan[0][i], manhattan[1][i], manhattan[2][i]);
        if(manhattan[2][i] == 0)
        {
          REQUIRE(manhattan[1][i] == 0);
        }
        if(manhattan[1][i] == 0)
        {
          REQUIRE(manhattan[0][i] == 0);
        }
      }

      for(usize tier = 0; tier < 3; tier++)
      {
        INFO("tier " << k_TierNames[tier]);
        const bool tierHasSeeds = std::any_of(manhattan[tier].cbegin(), manhattan[tier].cend(), [](int32 v) { return v == 0; });

        // I2  The -1 sentinel. featureId <= 0 always yields -1. When a tier has at least one
        //     seed, the converse also holds on these fixtures (their featureId > 0 regions are
        //     face-connected, so every such cell is reached). When a tier has no seed at all
        //     (fixtures E and F, and the TJ/QP tiers of A, B, Dz) every element stays -1.
        for(usize i = 0; i < numCells; i++)
        {
          CAPTURE(fixture.tag, k_TierNames[tier], i, fixture.featureIds[i], manhattan[tier][i], euclidean[tier][i]);
          if(fixture.featureIds[i] <= 0)
          {
            REQUIRE(manhattan[tier][i] == -1);
            REQUIRE(euclidean[tier][i] == -1.0F);
          }
          else if(tierHasSeeds)
          {
            REQUIRE(manhattan[tier][i] >= 0);
            REQUIRE(euclidean[tier][i] >= 0.0F);
          }
          else
          {
            REQUIRE(manhattan[tier][i] == -1);
            REQUIRE(euclidean[tier][i] == -1.0F);
          }
        }

        // I3  Adjacent Manhattan distances differ by at most 1. This is the defining property of
        //     a breadth-first graph distance on the featureId > 0 subgraph, and it is what fails
        //     if the distance commit is moved inside the sweep (the propagation stops being
        //     layer-synchronous).
        const int64 nX = static_cast<int64>(fixture.dims[0]);
        const int64 nY = static_cast<int64>(fixture.dims[1]);
        const int64 nZ = static_cast<int64>(fixture.dims[2]);
        for(int64 z = 0; z < nZ; z++)
        {
          for(int64 y = 0; y < nY; y++)
          {
            for(int64 x = 0; x < nX; x++)
            {
              const int64 i = (z * nX * nY) + (y * nX) + x;
              if(manhattan[tier][static_cast<usize>(i)] < 0)
              {
                continue;
              }
              const std::array<std::array<int64, 3>, 3> forwardOffsets = {{{1, 0, 0}, {0, 1, 0}, {0, 0, 1}}};
              for(const auto& offset : forwardOffsets)
              {
                const int64 nx2 = x + offset[0];
                const int64 ny2 = y + offset[1];
                const int64 nz2 = z + offset[2];
                if(nx2 >= nX || ny2 >= nY || nz2 >= nZ)
                {
                  continue;
                }
                const int64 j = (nz2 * nX * nY) + (ny2 * nX) + nx2;
                if(manhattan[tier][static_cast<usize>(j)] < 0)
                {
                  continue;
                }
                CAPTURE(fixture.tag, k_TierNames[tier], i, j, manhattan[tier][static_cast<usize>(i)], manhattan[tier][static_cast<usize>(j)]);
                REQUIRE(std::abs(manhattan[tier][static_cast<usize>(i)] - manhattan[tier][static_cast<usize>(j)]) <= 1);
              }
            }
          }
        }

        // I4  The seed sets of the two modes agree: a cell has Manhattan distance 0 exactly when
        //     it has euclidean distance 0, because both mean "the cell is its own nearest
        //     neighbour".
        for(usize i = 0; i < numCells; i++)
        {
          CAPTURE(fixture.tag, k_TierNames[tier], i, manhattan[tier][i], euclidean[tier][i]);
          REQUIRE((manhattan[tier][i] == 0) == (euclidean[tier][i] == 0.0F));
        }

        // I5  ED-1, stated as an inequality: the euclidean output is >= the true Euclidean
        //     distance transform pointwise, and is STRICTLY greater wherever the tie-break handed
        //     the cell a farther seed than the nearest one. `TrueEdt` is brute-forced here from
        //     the filter's own zero-set, not from the oracle table.
        const std::vector<float64> trueEdt = TrueEdt(fixture, manhattan[tier]);
        usize numStrict = 0;
        for(usize i = 0; i < numCells; i++)
        {
          if(euclidean[tier][i] < 0.0F || trueEdt[i] < 0.0)
          {
            continue;
          }
          CAPTURE(fixture.tag, k_TierNames[tier], i, euclidean[tier][i], trueEdt[i]);
          REQUIRE(static_cast<float64>(euclidean[tier][i]) >= trueEdt[i] - 1.0e-6);
          if(static_cast<float64>(euclidean[tier][i]) > trueEdt[i] + 1.0e-6)
          {
            numStrict++;
          }
        }
        // Fixture A's GB map is the ED-1 demonstrator: exactly three cells (0, 11, 17) are handed
        // a seed strictly farther than the nearest one. Cell 0 gets 4.0 where a boundary seed
        // sits 2.0 away.
        if(fixture.tag == "A" && tier == 0)
        {
          REQUIRE(numStrict == 3);
          REQUIRE(euclidean[0][0] == 4.0F);
          REQUIRE(trueEdt[0] == Approx(2.0).epsilon(1.0e-12));
        }
      }

      // I6  Toggle independence. In SIMPLNX a tier's output does not depend on which OTHER
      //     toggles were set, because the nearestNeighbors scratch vector is initialised to -1
      //     (Algorithms/ComputeEuclideanDistMap.cpp:314) and every component is written by the
      //     empty-coordination branch or by its own tier's branch. DREAM3D 6.5.171 zero-initialises
      //     the equivalent array and therefore breaks this invariant -- see the deviations doc.
      for(usize tier = 0; tier < 3; tier++)
      {
        DataStructure singleManhattanDS = BuildFixture(fixture);
        RunFilter(singleManhattanDS, true, k_ToggleSets[tier]);
        const std::vector<int32> singleManhattan = ReadInt32(singleManhattanDS, k_TierPaths[tier]);

        DataStructure singleEuclideanDS = BuildFixture(fixture);
        RunFilter(singleEuclideanDS, false, k_ToggleSets[tier]);
        const std::vector<float32> singleEuclidean = ReadFloat32(singleEuclideanDS, k_TierPaths[tier]);

        for(usize i = 0; i < numCells; i++)
        {
          CAPTURE(fixture.tag, k_TierNames[tier], i, singleManhattan[i], manhattan[tier][i], singleEuclidean[i], euclidean[tier][i]);
          REQUIRE(singleManhattan[i] == manhattan[tier][i]);
          REQUIRE(singleEuclidean[i] == euclidean[tier][i]);
        }
      }

      UnitTest::CheckArraysInheritTupleDims(manhattanDS);
      UnitTest::CheckArraysInheritTupleDims(euclideanDS);
    }
  }
}

TEST_CASE("SimplnxCore::ComputeEuclideanDistMapFilter: Parallel Determinism", "[SimplnxCore][ComputeEuclideanDistMapFilter]")
{
  UnitTest::LoadPlugins();

  // The three tiers are dispatched as three concurrent ParallelTaskAlgorithm tasks that share one
  // `std::vector<int64> nearestNeighbors` and both read the same FeatureIds DataStore. Each task
  // touches only its own component of the shared vector, so the output must be bit-identical run
  // to run. Repeated three times on the richest fixture, in both modes.
  const Fixture& fixture = *std::find_if(k_Fixtures.cbegin(), k_Fixtures.cend(), [](const Fixture& f) { return f.tag == "A"; });

  for(const bool calcManhattan : {true, false})
  {
    DYNAMIC_SECTION((calcManhattan ? "manhattan int32" : "euclidean float32"))
    {
      std::array<std::vector<int32>, 3> referenceInt;
      std::array<std::vector<float32>, 3> referenceFloat;
      // Declared outside the repeat loop so the last run's DataStructure survives for the
      // tuple-dimension check at the end of the section.
      DataStructure dataStructure;
      for(int32 repeat = 0; repeat < 3; repeat++)
      {
        dataStructure = BuildFixture(fixture);
        RunFilter(dataStructure, calcManhattan, k_ToggleSets.back());
        for(usize tier = 0; tier < 3; tier++)
        {
          if(calcManhattan)
          {
            const std::vector<int32> actual = ReadInt32(dataStructure, k_TierPaths[tier]);
            if(repeat == 0)
            {
              referenceInt[tier] = actual;
            }
            for(usize i = 0; i < actual.size(); i++)
            {
              CAPTURE(repeat, k_TierNames[tier], i, referenceInt[tier][i], actual[i]);
              REQUIRE(actual[i] == referenceInt[tier][i]);
            }
          }
          else
          {
            const std::vector<float32> actual = ReadFloat32(dataStructure, k_TierPaths[tier]);
            if(repeat == 0)
            {
              referenceFloat[tier] = actual;
            }
            for(usize i = 0; i < actual.size(); i++)
            {
              CAPTURE(repeat, k_TierNames[tier], i, referenceFloat[tier][i], actual[i]);
              REQUIRE(actual[i] == referenceFloat[tier][i]);
            }
          }
        }
      }

      UnitTest::CheckArraysInheritTupleDims(dataStructure);
    }
  }
}

TEST_CASE("SimplnxCore::ComputeEuclideanDistMapFilter: Error Paths", "[SimplnxCore][ComputeEuclideanDistMapFilter]")
{
  UnitTest::LoadPlugins();

  const Fixture& fixture = *std::find_if(k_Fixtures.cbegin(), k_Fixtures.cend(), [](const Fixture& f) { return f.tag == "C"; });

  SECTION("-12802 no output selected")
  {
    // DREAM3D 6.5.171 accepts all-toggles-false and silently produces nothing; SIMPLNX rejects it.
    // The guard is the better behaviour, so this is a documented deviation rather than a fix. The
    // message must also name the offending FeatureIds path -- it previously passed the path to
    // fmt::format with no `{}` placeholder to receive it, so the argument was dropped (ED-5).
    DataStructure dataStructure = BuildFixture(fixture);
    ComputeEuclideanDistMapFilter filter;
    const Arguments args = MakeArgs(true, ToggleSet{"none", false, false, false});
    auto preflightResult = filter.preflight(dataStructure, args);
    SIMPLNX_RESULT_REQUIRE_INVALID(preflightResult.outputActions)
    REQUIRE(preflightResult.outputActions.errors().size() == 1);
    REQUIRE(preflightResult.outputActions.errors()[0].code == -12802);
    const std::string message = preflightResult.outputActions.errors()[0].message;
    CAPTURE(message);
    REQUIRE(message.find(k_TestFeatureIdsPath.toString()) != std::string::npos);

    UnitTest::CheckArraysInheritTupleDims(dataStructure);
  }

  SECTION("-12803 FeatureIds tuple count does not match the geometry cell count")
  {
    // ED-3. `nearestNeighbors` is sized from the FeatureIds tuple count
    // (Algorithms/ComputeEuclideanDistMap.cpp:290, 314) but the propagation phase iterates the
    // GEOMETRY's cell count (:60), so a FeatureIds selection with fewer tuples than the selected
    // geometry has cells reads and writes past the end of the scratch vector. Preflight must
    // reject the mismatch instead. Only preflight is exercised: executing this configuration is
    // the out-of-bounds access itself.
    DataStructure dataStructure;
    auto* imageGeom = ImageGeom::Create(dataStructure, k_TestImageGeomName);
    imageGeom->setDimensions(SizeVec3{3, 3, 1}); // 9 cells
    imageGeom->setSpacing(FloatVec3{1.0F, 1.0F, 1.0F});
    auto* cellData = AttributeMatrix::Create(dataStructure, k_TestCellDataName, ShapeType{8}, imageGeom->getId());
    auto storePtr = std::make_shared<Int32DataStore>(ShapeType{8}, ShapeType{1}, 1); // 8 tuples
    Int32Array::Create(dataStructure, k_TestFeatureIdsName, storePtr, cellData->getId());

    ComputeEuclideanDistMapFilter filter;
    const Arguments args = MakeArgs(true, k_ToggleSets.back());
    auto preflightResult = filter.preflight(dataStructure, args);
    SIMPLNX_RESULT_REQUIRE_INVALID(preflightResult.outputActions)
    REQUIRE(preflightResult.outputActions.errors().size() == 1);
    REQUIRE(preflightResult.outputActions.errors()[0].code == -12803);
    const std::string message = preflightResult.outputActions.errors()[0].message;
    CAPTURE(message);
    // Both actual counts, both offending paths and the geometry dimensions must appear so the user
    // can fix it from the message alone. Asserted as whole phrases, not as single digits, so the
    // assertions cannot pass on an unrelated numeral elsewhere in the message.
    REQUIRE(message.find("has 8 tuples") != std::string::npos);
    REQUIRE(message.find("has 9 cells (3x3x1)") != std::string::npos);
    REQUIRE(message.find(k_TestFeatureIdsPath.toString()) != std::string::npos);
    REQUIRE(message.find(k_TestImageGeomPath.toString()) != std::string::npos);

    UnitTest::CheckArraysInheritTupleDims(dataStructure);
  }

  SECTION("-12803 does not fire when the counts agree")
  {
    DataStructure dataStructure = BuildFixture(fixture);
    ComputeEuclideanDistMapFilter filter;
    const Arguments args = MakeArgs(true, k_ToggleSets.back());
    auto preflightResult = filter.preflight(dataStructure, args);
    SIMPLNX_RESULT_REQUIRE_VALID(preflightResult.outputActions)

    UnitTest::CheckArraysInheritTupleDims(dataStructure);
  }
}

TEST_CASE("SimplnxCore::ComputeEuclideanDistMap", "[SimplnxCore][ComputeEuclideanDistMap]")
{
  UnitTest::LoadPlugins();

  const nx::core::UnitTest::TestFileSentinel testDataSentinel(nx::core::unit_test::k_TestFilesDir, "6_6_stats_test_v2.tar.gz", "6_6_stats_test_v2.dream3d");

  // Read the Small IN100 Data set
  auto baseDataFilePath = fs::path(fmt::format("{}/6_6_stats_test_v2.dream3d", unit_test::k_TestFilesDir));
  const DataPath k_CellFeatureDataAM = k_DataContainerPath.createChildPath("CellFeatureData");

  // Run a matrix of scenarios. In each scenario exactly one calculated output is expected to exist and match its exemplar.
  auto [scenarioName, doBoundaries, doTripleLines, doQuadPoints, expectedArrayName] = GENERATE(std::make_tuple("Boundaries only (GB distances)", true, false, false, k_GBDistancesArrayName),
                                                                                               std::make_tuple("Triple lines only (TJ distances)", false, true, false, k_TJDistancesArrayName),
                                                                                               std::make_tuple("Quad points only (QP distances)", false, false, true, k_QPDistancesArrayName));

  INFO("Scenario: " << scenarioName);

  DataStructure dataStructure = UnitTest::LoadDataStructure(baseDataFilePath);

  {
    ComputeEuclideanDistMapFilter filter;
    Arguments args;

    // Parameters
    args.insert(ComputeEuclideanDistMapFilter::k_CalcManhattanDist_Key, std::make_any<bool>(true));
    args.insert(ComputeEuclideanDistMapFilter::k_DoBoundaries_Key, std::make_any<bool>(doBoundaries));
    args.insert(ComputeEuclideanDistMapFilter::k_DoTripleLines_Key, std::make_any<bool>(doTripleLines));
    args.insert(ComputeEuclideanDistMapFilter::k_DoQuadPoints_Key, std::make_any<bool>(doQuadPoints));

    // Input Arrays
    args.insert(ComputeEuclideanDistMapFilter::k_SelectedImageGeometryPath_Key, std::make_any<DataPath>(k_DataContainerPath));
    args.insert(ComputeEuclideanDistMapFilter::k_CellFeatureIdsArrayPath_Key, std::make_any<DataPath>(k_CellAttributeMatrix.createChildPath(k_FeatureIds)));

    // Output Arrays
    args.insert(ComputeEuclideanDistMapFilter::k_GBDistancesArrayName_Key, std::make_any<std::string>(k_CalculatedPrefix + k_GBDistancesArrayName));
    args.insert(ComputeEuclideanDistMapFilter::k_TJDistancesArrayName_Key, std::make_any<std::string>(k_CalculatedPrefix + k_TJDistancesArrayName));
    args.insert(ComputeEuclideanDistMapFilter::k_QPDistancesArrayName_Key, std::make_any<std::string>(k_CalculatedPrefix + k_QPDistancesArrayName));

    // Preflight the filter and check result
    auto preflightResult = filter.preflight(dataStructure, args);
    SIMPLNX_RESULT_REQUIRE_VALID(preflightResult.outputActions)

    // Execute the filter and check the result
    auto executeResult = filter.execute(dataStructure, args);
    SIMPLNX_RESULT_REQUIRE_VALID(executeResult.result)
  }

  // Check that the appropriate array exists and the others don't exist
  for(const auto& outputName : {k_GBDistancesArrayName, k_TJDistancesArrayName, k_QPDistancesArrayName})
  {
    const bool shouldExist = (outputName == expectedArrayName);
    INFO("  Output: " << outputName << " (expected " << (shouldExist ? "present" : "absent") << ")");

    if(shouldExist)
    {
      REQUIRE(ArrayExists(dataStructure, outputName));
    }
    else
    {
      REQUIRE_FALSE(ArrayExists(dataStructure, outputName));
    }
  }

  // Check that the currently enabled array matches its exemplar
  const DataPath exemplarPath({k_DataContainer, k_CellData, expectedArrayName});
  const DataPath calculatedPath({k_DataContainer, k_CellData, k_CalculatedPrefix + expectedArrayName});
  const auto& exemplarData = dataStructure.getDataRefAs<IDataArray>(exemplarPath);
  const auto& calculatedData = dataStructure.getDataRefAs<IDataArray>(calculatedPath);
  UnitTest::CompareDataArrays<int32>(exemplarData, calculatedData);

  UnitTest::CheckArraysInheritTupleDims(dataStructure);
}

TEST_CASE("SimplnxCore::ComputeEuclideanDistMapFilter: SIMPL Backwards Compatibility", "[SimplnxCore][ComputeEuclideanDistMapFilter][BackwardsCompatibility]")
{
  auto app = Application::GetOrCreateInstance();
  UnitTest::LoadPlugins();
  auto filterList = app->getFilterList();

  const fs::path conversionDir = fs::path(nx::core::unit_test::k_SourceDir.view()) / "test" / "simpl_conversion";

  const std::vector<std::pair<std::string, fs::path>> fixtures = {
      {"SIMPL 6.5 (UUID)", conversionDir / "6_5" / "ComputeEuclideanDistMapFilter.json"},
      {"SIMPL 6.4 (Filter_Name)", conversionDir / "6_4" / "ComputeEuclideanDistMapFilter.json"},
  };

  for(const auto& [label, fixturePath] : fixtures)
  {
    DYNAMIC_SECTION(label)
    {
      auto pipelineResult = Pipeline::FromSIMPLFile(fixturePath, filterList);
      REQUIRE(pipelineResult.valid());

      auto& pipeline = pipelineResult.value();
      REQUIRE(pipeline.size() == 1);

      auto* pipelineFilter = dynamic_cast<PipelineFilter*>(pipeline.at(0));
      REQUIRE(pipelineFilter != nullptr);

      const IFilter* filter = pipelineFilter->getFilter();
      REQUIRE(filter != nullptr);
      REQUIRE(filter->uuid() == FilterTraits<ComputeEuclideanDistMapFilter>::uuid);

      CHECK(pipelineFilter->getComments().empty());

      const Arguments args = pipelineFilter->getArguments();
      CHECK(args.value<bool>(ComputeEuclideanDistMapFilter::k_CalcManhattanDist_Key) == true);
      CHECK(args.value<bool>(ComputeEuclideanDistMapFilter::k_DoBoundaries_Key) == true);
      CHECK(args.value<bool>(ComputeEuclideanDistMapFilter::k_DoTripleLines_Key) == true);
      CHECK(args.value<bool>(ComputeEuclideanDistMapFilter::k_DoQuadPoints_Key) == true);
      CHECK(args.value<DataPath>(ComputeEuclideanDistMapFilter::k_SelectedImageGeometryPath_Key) == DataPath({"DataContainer"}));
      CHECK(args.value<DataPath>(ComputeEuclideanDistMapFilter::k_CellFeatureIdsArrayPath_Key) == DataPath({"DataContainer", "CellData", "TestArray"}));
      CHECK(args.value<std::string>(ComputeEuclideanDistMapFilter::k_GBDistancesArrayName_Key) == "TestName");
      CHECK(args.value<std::string>(ComputeEuclideanDistMapFilter::k_TJDistancesArrayName_Key) == "TestName");
      CHECK(args.value<std::string>(ComputeEuclideanDistMapFilter::k_QPDistancesArrayName_Key) == "TestName");
    }
  }
}
