#include "SimplnxCore/Filters/WriteDAMASKFilesFilter.hpp"
#include "SimplnxCore/SimplnxCore_test_dirs.hpp"

#include "simplnx/Core/Application.hpp"
#include "simplnx/DataStructure/AttributeMatrix.hpp"
#include "simplnx/DataStructure/DataArray.hpp"
#include "simplnx/DataStructure/Geometry/ImageGeom.hpp"
#include "simplnx/Parameters/FileSystemPathParameter.hpp"
#include "simplnx/Parameters/StringParameter.hpp"
#include "simplnx/Pipeline/Pipeline.hpp"
#include "simplnx/Pipeline/PipelineFilter.hpp"
#include "simplnx/UnitTest/UnitTestCommon.hpp"
#include "simplnx/Utilities/DataStoreUtilities.hpp"

#include <catch2/catch.hpp>

#include <algorithm>
#include <chrono>
#include <filesystem>
#include <fstream>
#include <iterator>
#include <numbers>
#include <string>
#include <vector>

namespace fs = std::filesystem;
using namespace nx::core;

namespace
{
const DataPath k_ImageGeomPath({"Image Geometry"});
const DataPath k_CellDataPath = k_ImageGeomPath.createChildPath("Cell Data");
const DataPath k_FeatureIdsPath = k_CellDataPath.createChildPath("FeatureIds");
const DataPath k_EulerAnglesPath = k_CellDataPath.createChildPath("EulerAngles");
const DataPath k_PhasesPath = k_CellDataPath.createChildPath("Phases");
const DataPath k_WrongPhasesPath({"Wrong Phases"});

const std::string k_PointwiseMaterial = R"(#############################################################################
# Generated by DREAM.3D
#############################################################################
# Add <homogenization>, <crystallite>, and <phase> for a complete definition
#############################################################################
<texture>
[point1]
(gauss) phi1 0.000   Phi 0.000    phi2 0.000   scatter 0.0   fraction 1.0)"
                                        " \n"
                                        R"([point2]
(gauss) phi1 15.000   Phi 22.500    phi2 30.000   scatter 0.0   fraction 1.0)"
                                        " \n"
                                        R"([point3]
(gauss) phi1 30.000   Phi 45.000    phi2 60.000   scatter 0.0   fraction 1.0)"
                                        " \n"
                                        R"([point4]
(gauss) phi1 45.000   Phi 67.500    phi2 90.000   scatter 0.0   fraction 1.0)"
                                        " \n"
                                        R"([point5]
(gauss) phi1 60.000   Phi 90.000    phi2 120.000   scatter 0.0   fraction 1.0)"
                                        " \n"
                                        R"([point6]
(gauss) phi1 75.000   Phi 112.500    phi2 150.000   scatter 0.0   fraction 1.0)"
                                        " \n"
                                        R"(<microstructure>
[point1]
crystallite 1
(constituent)   phase 1 texture 1 fraction 1.0
[point2]
crystallite 1
(constituent)   phase 1 texture 2 fraction 1.0
[point3]
crystallite 1
(constituent)   phase 1 texture 3 fraction 1.0
[point4]
crystallite 1
(constituent)   phase 2 texture 4 fraction 1.0
[point5]
crystallite 1
(constituent)   phase 2 texture 5 fraction 1.0
[point6]
crystallite 1
(constituent)   phase 2 texture 6 fraction 1.0
)";

DataStructure CreateDataStructure(const SizeVec3& dimensions, const FloatVec3& spacing, const FloatVec3& origin, const std::vector<int32>& featureIds, const std::vector<int32>& phases,
                                  const std::vector<float32>& eulerAngles)
{
  DataStructure dataStructure;
  auto* imageGeom = ImageGeom::Create(dataStructure, k_ImageGeomPath.getTargetName());
  REQUIRE(imageGeom != nullptr);
  imageGeom->setDimensions(dimensions);
  imageGeom->setSpacing(spacing);
  imageGeom->setOrigin(origin);

  const ShapeType cellShape = {dimensions[2], dimensions[1], dimensions[0]};
  auto* cellData = AttributeMatrix::Create(dataStructure, k_CellDataPath.getTargetName(), cellShape, imageGeom->getId());
  REQUIRE(cellData != nullptr);
  imageGeom->setCellData(*cellData);

  auto featureIdsStore = DataStoreUtilities::CreateDataStore<int32>(cellShape, {1}, IDataAction::Mode::Execute);
  auto* featureIdsArray = DataArray<int32>::Create(dataStructure, k_FeatureIdsPath.getTargetName(), featureIdsStore, cellData->getId());
  REQUIRE(featureIdsArray != nullptr);

  auto phasesStore = DataStoreUtilities::CreateDataStore<int32>(cellShape, {1}, IDataAction::Mode::Execute);
  auto* phasesArray = DataArray<int32>::Create(dataStructure, k_PhasesPath.getTargetName(), phasesStore, cellData->getId());
  REQUIRE(phasesArray != nullptr);

  auto eulerAnglesStore = DataStoreUtilities::CreateDataStore<float32>(cellShape, {3}, IDataAction::Mode::Execute);
  auto* eulerAnglesArray = DataArray<float32>::Create(dataStructure, k_EulerAnglesPath.getTargetName(), eulerAnglesStore, cellData->getId());
  REQUIRE(eulerAnglesArray != nullptr);

  REQUIRE(featureIds.size() == featureIdsArray->getNumberOfTuples());
  REQUIRE(phases.size() == phasesArray->getNumberOfTuples());
  REQUIRE(eulerAngles.size() == eulerAnglesArray->getSize());
  std::copy(featureIds.cbegin(), featureIds.cend(), featureIdsArray->begin());
  std::copy(phases.cbegin(), phases.cend(), phasesArray->begin());
  std::copy(eulerAngles.cbegin(), eulerAngles.cend(), eulerAnglesArray->begin());
  return dataStructure;
}

std::vector<float32> CreateEulerAngles(usize cellCount)
{
  constexpr float32 k_Pi = std::numbers::pi_v<float32>;
  std::vector<float32> eulerAngles(cellCount * 3);
  for(usize cellIndex = 0; cellIndex < cellCount; cellIndex++)
  {
    const float32 index = static_cast<float32>(cellIndex);
    eulerAngles[cellIndex * 3] = index * k_Pi / 12.0F;
    eulerAngles[cellIndex * 3 + 1] = index * k_Pi / 8.0F;
    eulerAngles[cellIndex * 3 + 2] = index * k_Pi / 6.0F;
  }
  return eulerAngles;
}

Arguments CreateArguments(const fs::path& outputPath, const std::string& geometryFileName, uint64 dataFormat = 0, bool compressGeomFile = false)
{
  Arguments args = WriteDAMASKFilesFilter().getDefaultArguments();
  args.insertOrAssign(WriteDAMASKFilesFilter::k_DataFormat_Key, std::make_any<uint64>(dataFormat));
  args.insertOrAssign(WriteDAMASKFilesFilter::k_OutputPath_Key, std::make_any<FileSystemPathParameter::ValueType>(outputPath));
  args.insertOrAssign(WriteDAMASKFilesFilter::k_GeometryFileName_Key, std::make_any<StringParameter::ValueType>(geometryFileName));
  args.insertOrAssign(WriteDAMASKFilesFilter::k_HomogenizationIndex_Key, std::make_any<int32>(2));
  args.insertOrAssign(WriteDAMASKFilesFilter::k_CompressGeomFile_Key, std::make_any<bool>(compressGeomFile));
  args.insertOrAssign(WriteDAMASKFilesFilter::k_ImageGeometryPath_Key, std::make_any<DataPath>(k_ImageGeomPath));
  args.insertOrAssign(WriteDAMASKFilesFilter::k_FeatureIdsArrayPath_Key, std::make_any<DataPath>(k_FeatureIdsPath));
  args.insertOrAssign(WriteDAMASKFilesFilter::k_CellEulerAnglesArrayPath_Key, std::make_any<DataPath>(k_EulerAnglesPath));
  args.insertOrAssign(WriteDAMASKFilesFilter::k_CellPhasesArrayPath_Key, std::make_any<DataPath>(k_PhasesPath));
  return args;
}

std::string ReadFile(const fs::path& filePath)
{
  std::ifstream input(filePath, std::ios::binary);
  REQUIRE(input.is_open());
  return {std::istreambuf_iterator<char>(input), std::istreambuf_iterator<char>()};
}
} // namespace

TEST_CASE("SimplnxCore::WriteDAMASKFilesFilter: Pointwise Uncompressed", "[SimplnxCore][WriteDAMASKFilesFilter]")
{
  UnitTest::LoadPlugins();
  DataStructure dataStructure = CreateDataStructure({3, 2, 1}, {0.5F, 0.25F, 2.0F}, {1.0F, -1.0F, 0.5F}, {1, 1, 2, 2, 3, 3}, {1, 1, 1, 2, 2, 2}, CreateEulerAngles(6));
  const fs::path outputPath = fs::path(unit_test::k_BinaryTestOutputDir.view()) / "WriteDAMASKFiles" / "PointwiseUncompressed";
  fs::create_directories(outputPath);
  const WriteDAMASKFilesFilter filter;
  Arguments args = CreateArguments(outputPath, "damask_test");

  auto preflightResult = filter.preflight(dataStructure, args);
  SIMPLNX_RESULT_REQUIRE_VALID(preflightResult.outputActions);
  auto executeResult = filter.execute(dataStructure, args);
  SIMPLNX_RESULT_REQUIRE_VALID(executeResult.result);

  const std::string expectedGeometry = R"(6       header
# Generated by DREAM.3D
grid    a 3    b 2    c 1
size    x 1.500    y 0.500    z 2.000
origin    x 1.000    y -1.000    z 0.500
homogenization  2
microstructures 6
         1          2          3
         4          5          6)";
  REQUIRE(ReadFile(outputPath / "damask_test.geom") == expectedGeometry);
  REQUIRE(ReadFile(outputPath / "material.config") == k_PointwiseMaterial);
  UnitTest::CheckArraysInheritTupleDims(dataStructure);
}

TEST_CASE("SimplnxCore::WriteDAMASKFilesFilter: Pointwise Compressed", "[SimplnxCore][WriteDAMASKFilesFilter]")
{
  UnitTest::LoadPlugins();
  DataStructure dataStructure = CreateDataStructure({3, 2, 1}, {0.5F, 0.25F, 2.0F}, {1.0F, -1.0F, 0.5F}, {1, 1, 2, 2, 3, 3}, {1, 1, 1, 2, 2, 2}, CreateEulerAngles(6));
  const fs::path outputPath = fs::path(unit_test::k_BinaryTestOutputDir.view()) / "WriteDAMASKFiles" / "PointwiseCompressed";
  fs::create_directories(outputPath);
  const WriteDAMASKFilesFilter filter;
  Arguments args = CreateArguments(outputPath, "damask_test", 0, true);

  auto executeResult = filter.execute(dataStructure, args);
  SIMPLNX_RESULT_REQUIRE_VALID(executeResult.result);
  const std::string geometry = ReadFile(outputPath / "damask_test.geom");
  REQUIRE(geometry.ends_with("microstructures 6\n1 to          6"));
  REQUIRE_FALSE(geometry.ends_with('\n'));
  REQUIRE(ReadFile(outputPath / "material.config") == k_PointwiseMaterial);
  UnitTest::CheckArraysInheritTupleDims(dataStructure);
}

TEST_CASE("SimplnxCore::WriteDAMASKFilesFilter: Grainwise With Gap", "[SimplnxCore][WriteDAMASKFilesFilter]")
{
  UnitTest::LoadPlugins();
  DataStructure dataStructure = CreateDataStructure({4, 1, 1}, {1.0F, 1.0F, 1.0F}, {0.0F, 0.0F, 0.0F}, {1, 1, 3, 0}, {1, 1, 2, 2}, CreateEulerAngles(4));
  const fs::path outputPath = fs::path(unit_test::k_BinaryTestOutputDir.view()) / "WriteDAMASKFiles" / "GrainwiseWithGap";
  fs::create_directories(outputPath);
  const WriteDAMASKFilesFilter filter;
  Arguments args = CreateArguments(outputPath, "grainwise", 1);
  usize warningCount = 0;
  std::string warningText;
  const IFilter::MessageHandler messageHandler{[&](const IFilter::Message& message) {
    if(message.type == IFilter::Message::Type::Warning)
    {
      warningCount++;
      warningText = message.message;
    }
  }};

  auto executeResult = filter.execute(dataStructure, args, nullptr, messageHandler);
  SIMPLNX_RESULT_REQUIRE_VALID(executeResult.result);
  const std::string expectedGeometry = R"(6       header
# Generated by DREAM.3D
grid    a 4    b 1    c 1
size    x 4.000    y 1.000    z 1.000
origin    x 0.000    y 0.000    z 0.000
homogenization  2
microstructures 3
         1          1          3          0)";
  const std::string expectedMaterial = R"(#############################################################################
# Generated by DREAM.3D
#############################################################################
# Add <homogenization>, <crystallite>, and <phase> for a complete definition
#############################################################################
<texture>
[grain1]
(gauss) phi1 15.000   Phi 22.500    phi2 30.000   scatter 0.0   fraction 1.0)"
                                       " \n"
                                       R"([grain2]
(gauss) phi1 0.000   Phi 0.000    phi2 0.000   scatter 0.0   fraction 1.0)"
                                       " \n"
                                       R"([grain3]
(gauss) phi1 30.000   Phi 45.000    phi2 60.000   scatter 0.0   fraction 1.0)"
                                       " \n"
                                       R"(<microstructure>
[grain1]
crystallite 1
(constituent)   phase 1 texture 1 fraction 1.0
[grain2]
crystallite 1
(constituent)   phase 0 texture 2 fraction 1.0
[grain3]
crystallite 1
(constituent)   phase 2 texture 3 fraction 1.0
)";
  REQUIRE(ReadFile(outputPath / "grainwise.geom") == expectedGeometry);
  REQUIRE(ReadFile(outputPath / "material.config") == expectedMaterial);
  REQUIRE(warningCount == 1);
  REQUIRE(warningText.find("1 grain") != std::string::npos);
  REQUIRE(warningText.find("no cells") != std::string::npos);
  UnitTest::CheckArraysInheritTupleDims(dataStructure);
}

TEST_CASE("SimplnxCore::WriteDAMASKFilesFilter: Grainwise No Positive Ids Fails", "[SimplnxCore][WriteDAMASKFilesFilter]")
{
  UnitTest::LoadPlugins();
  DataStructure dataStructure = CreateDataStructure({3, 1, 1}, {1.0F, 1.0F, 1.0F}, {0.0F, 0.0F, 0.0F}, {0, 0, 0}, {1, 1, 1}, CreateEulerAngles(3));
  const auto uniqueSuffix = std::chrono::high_resolution_clock::now().time_since_epoch().count();
  const fs::path outputPath = fs::path(unit_test::k_BinaryTestOutputDir.view()) / fmt::format("WriteDAMASKFiles_NoPositiveIds_{}", uniqueSuffix);
  fs::create_directories(outputPath);
  const WriteDAMASKFilesFilter filter;
  Arguments args = CreateArguments(outputPath, "no_grains", 1);

  auto executeResult = filter.execute(dataStructure, args);
  REQUIRE(executeResult.result.invalid());
  REQUIRE(executeResult.result.errors().size() == 1);
  REQUIRE(executeResult.result.errors()[0].code == -12074);
  REQUIRE_FALSE(fs::exists(outputPath / "no_grains.geom"));
  REQUIRE_FALSE(fs::exists(outputPath / "material.config"));
  UnitTest::CheckArraysInheritTupleDims(dataStructure);
}

TEST_CASE("SimplnxCore::WriteDAMASKFilesFilter: Row Wrapping", "[SimplnxCore][WriteDAMASKFilesFilter]")
{
  UnitTest::LoadPlugins();
  std::vector<int32> featureIds(18, 1);
  std::vector<int32> phases(18, 1);
  DataStructure dataStructure = CreateDataStructure({3, 3, 2}, {1.0F, 1.0F, 1.0F}, {0.0F, 0.0F, 0.0F}, featureIds, phases, CreateEulerAngles(18));
  const fs::path outputPath = fs::path(unit_test::k_BinaryTestOutputDir.view()) / "WriteDAMASKFiles" / "RowWrapping";
  fs::create_directories(outputPath);
  const WriteDAMASKFilesFilter filter;
  Arguments args = CreateArguments(outputPath, "row_wrapping");

  auto executeResult = filter.execute(dataStructure, args);
  SIMPLNX_RESULT_REQUIRE_VALID(executeResult.result);
  const std::string geometry = ReadFile(outputPath / "row_wrapping.geom");
  const std::string expectedBody = R"(         1          2          3
         4          5          6
         7          8          9
        10         11         12
        13         14         15
        16         17         18)";
  REQUIRE(geometry.ends_with(expectedBody));
  UnitTest::CheckArraysInheritTupleDims(dataStructure);
}

TEST_CASE("SimplnxCore::WriteDAMASKFilesFilter: Empty Geometry File Name", "[SimplnxCore][WriteDAMASKFilesFilter]")
{
  UnitTest::LoadPlugins();
  DataStructure dataStructure = CreateDataStructure({1, 1, 1}, {1.0F, 1.0F, 1.0F}, {0.0F, 0.0F, 0.0F}, {1}, {1}, CreateEulerAngles(1));
  const WriteDAMASKFilesFilter filter;
  Arguments args = CreateArguments(fs::path(unit_test::k_BinaryTestOutputDir.view()), "");
  auto preflightResult = filter.preflight(dataStructure, args);
  REQUIRE(preflightResult.outputActions.invalid());
  REQUIRE(preflightResult.outputActions.errors()[0].code == -12072);
}

TEST_CASE("SimplnxCore::WriteDAMASKFilesFilter: Missing Output Directory", "[SimplnxCore][WriteDAMASKFilesFilter]")
{
  UnitTest::LoadPlugins();
  DataStructure dataStructure = CreateDataStructure({1, 1, 1}, {1.0F, 1.0F, 1.0F}, {0.0F, 0.0F, 0.0F}, {1}, {1}, CreateEulerAngles(1));
  const auto uniqueSuffix = std::chrono::high_resolution_clock::now().time_since_epoch().count();
  const fs::path missingPath = fs::path(unit_test::k_BinaryTestOutputDir.view()) / fmt::format("WriteDAMASKFiles_Missing_{}", uniqueSuffix);
  REQUIRE_FALSE(fs::exists(missingPath));
  const WriteDAMASKFilesFilter filter;
  Arguments args = CreateArguments(missingPath, "missing");
  auto preflightResult = filter.preflight(dataStructure, args);
  REQUIRE(preflightResult.outputActions.invalid());
  REQUIRE(preflightResult.outputActions.errors()[0].code == -12070);
  REQUIRE(preflightResult.outputActions.errors()[0].message.find(missingPath.string()) != std::string::npos);
}

TEST_CASE("SimplnxCore::WriteDAMASKFilesFilter: Tuple Count Mismatch", "[SimplnxCore][WriteDAMASKFilesFilter]")
{
  UnitTest::LoadPlugins();
  DataStructure dataStructure = CreateDataStructure({2, 2, 1}, {1.0F, 1.0F, 1.0F}, {0.0F, 0.0F, 0.0F}, {1, 1, 1, 1}, {1, 1, 1, 1}, CreateEulerAngles(4));
  auto wrongPhasesStore = DataStoreUtilities::CreateDataStore<int32>({3}, {1}, IDataAction::Mode::Execute);
  auto* wrongPhasesArray = DataArray<int32>::Create(dataStructure, k_WrongPhasesPath.getTargetName(), wrongPhasesStore);
  REQUIRE(wrongPhasesArray != nullptr);
  const WriteDAMASKFilesFilter filter;
  Arguments args = CreateArguments(fs::path(unit_test::k_BinaryTestOutputDir.view()), "mismatch");
  args.insertOrAssign(WriteDAMASKFilesFilter::k_CellPhasesArrayPath_Key, std::make_any<DataPath>(k_WrongPhasesPath));
  auto preflightResult = filter.preflight(dataStructure, args);
  REQUIRE(preflightResult.outputActions.invalid());
  REQUIRE(preflightResult.outputActions.errors()[0].code == -12077);
  REQUIRE(preflightResult.outputActions.errors()[0].message.find(k_WrongPhasesPath.toString()) != std::string::npos);
  REQUIRE(preflightResult.outputActions.errors()[0].message.find("3") != std::string::npos);
  REQUIRE(preflightResult.outputActions.errors()[0].message.find("4") != std::string::npos);
}

TEST_CASE("SimplnxCore::WriteDAMASKFilesFilter: SIMPL Backwards Compatibility", "[SimplnxCore][WriteDAMASKFilesFilter]")
{
  auto app = Application::GetOrCreateInstance();
  UnitTest::LoadPlugins();
  auto filterList = app->getFilterList();
  const fs::path conversionDir = fs::path(unit_test::k_SourceDir.view()) / "test" / "simpl_conversion";
  const std::vector<std::pair<std::string, fs::path>> fixtures = {
      {"SIMPL 6.5 (UUID)", conversionDir / "6_5" / "WriteDAMASKFilesFilter.json"},
      {"SIMPL 6.4 (Filter_Name)", conversionDir / "6_4" / "WriteDAMASKFilesFilter.json"},
  };

  for(usize fixtureIndex = 0; fixtureIndex < fixtures.size(); fixtureIndex++)
  {
    const auto& [label, fixturePath] = fixtures[fixtureIndex];
    DYNAMIC_SECTION(label)
    {
      auto pipelineResult = Pipeline::FromSIMPLFile(fixturePath, filterList);
      REQUIRE(pipelineResult.valid());
      auto& pipeline = pipelineResult.value();
      REQUIRE(pipeline.size() == 1);
      auto* pipelineFilter = dynamic_cast<PipelineFilter*>(pipeline.at(0));
      REQUIRE(pipelineFilter != nullptr);
      const IFilter* filter = pipelineFilter->getFilter();
      REQUIRE(filter != nullptr);
      REQUIRE(filter->uuid() == FilterTraits<WriteDAMASKFilesFilter>::uuid);

      const Arguments args = pipelineFilter->getArguments();
      CHECK(args.value<uint64>(WriteDAMASKFilesFilter::k_DataFormat_Key) == (fixtureIndex == 0 ? 1 : 0));
      CHECK(args.value<FileSystemPathParameter::ValueType>(WriteDAMASKFilesFilter::k_OutputPath_Key) == fs::path("/test/path"));
      CHECK(args.value<std::string>(WriteDAMASKFilesFilter::k_GeometryFileName_Key) == "damask_geometry");
      CHECK(args.value<int32>(WriteDAMASKFilesFilter::k_HomogenizationIndex_Key) == 3);
      CHECK(args.value<bool>(WriteDAMASKFilesFilter::k_CompressGeomFile_Key) == (fixtureIndex == 0));
      CHECK(args.value<DataPath>(WriteDAMASKFilesFilter::k_ImageGeometryPath_Key) == DataPath({"DataContainer"}));
      CHECK(args.value<DataPath>(WriteDAMASKFilesFilter::k_FeatureIdsArrayPath_Key) == DataPath({"DataContainer", "CellData", "FeatureIds"}));
      CHECK(args.value<DataPath>(WriteDAMASKFilesFilter::k_CellEulerAnglesArrayPath_Key) == DataPath({"DataContainer", "CellData", "EulerAngles"}));
      CHECK(args.value<DataPath>(WriteDAMASKFilesFilter::k_CellPhasesArrayPath_Key) == DataPath({"DataContainer", "CellData", "Phases"}));
    }
  }
}
